### ISSUE TITLE
Netlist library fails to compile on Windows MinGW 32-bit GCC 9.2.0

### ISSUE THREAD

**Issue by cuavas** [mamedev/mame#7006]
As of 60bd3086cc826664a46fc7e703a11e6518482e01, attempting a 32-bit build fails with this error in many source files:
```
In file included from ../../../../../src/lib/netlist/nltypes.h:20,
                 from ../../../../../src/lib/netlist/nl_setup.h:19,
                 from ../../../../../src/lib/netlist/devices/nld_7474.h:45,
                 from ../../../../../src/lib/netlist/devices/nld_7474.cpp:9:
../../../../../src/lib/netlist/plib/ppmf.h: In instantiation of 'class plib::pmfp_base<0, 0, void>':
../../../../../src/lib/netlist/core/base_objects.h:300:15:   required from here
../../../../../src/lib/netlist/plib/ppmf.h:327:9: error: no class template named 'const_specific_member_function' in 'struct plib::mfp_helper<0, 0, void>'
  327 |   using const_specific_member_function = typename helper::template const_specific_member_function<C>;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../src/lib/netlist/plib/ppmf.h: In instantiation of 'class plib::pmfp_base<0, 0, unsigned int, const netlist::detail::net_t*>':
../../../../../src/lib/netlist/nl_base.h:610:16:   required from 'class netlist::detail::queue_base<netlist::detail::net_t, false>'
../../../../../src/lib/netlist/nl_base.h:993:39:   required from here
../../../../../src/lib/netlist/plib/ppmf.h:327:9: error: no class template named 'const_specific_member_function' in 'struct plib::mfp_helper<0, 0, unsigned int, const netlist::detail::net_t*>'
../../../../../src/lib/netlist/plib/ppmf.h: In instantiation of 'class plib::pmfp_base<0, 0, netlist::detail::net_t*, unsigned int>':
../../../../../src/lib/netlist/nl_base.h:611:17:   required from 'class netlist::detail::queue_base<netlist::detail::net_t, false>'
../../../../../src/lib/netlist/nl_base.h:993:39:   required from here
../../../../../src/lib/netlist/plib/ppmf.h:327:9: error: no class template named 'const_specific_member_function' in 'struct plib::mfp_helper<0, 0, netlist::detail::net_t*, unsigned int>'
```

Standard MSYS2 x86-64 installation with GCC 9.2.0.
