### ISSUE TITLE
MAME doesn't build with Clang 20.1.0 on Windows

### ISSUE THREAD

**Issue by Osso13** [mamedev/mame#13453]
Yesterday pacman started distributing Clang 20.1.0. MAME fails to build. This will be a problem when the CI starts pulling that Clang version. There are problems both in 3rdparty and in MAME proper. This is an example of the latter:

../../../../../src/devices/cpu/alto2/a2disp.cpp:502:9: error: first argument in call to 'memset' is a pointer to
      non-trivially copyable type 'struct (unnamed struct at ../../../../../src/devices/cpu/alto2/a2disp.h:195:1)'
      [-Werror,-Wnontrivial-memcall]
  502 |         memset(&m_dsp, 0, sizeof(m_dsp));
      |                ^
../../../../../src/devices/cpu/alto2/a2disp.cpp:502:9: note: explicitly cast the pointer to silence this warning
  502 |         memset(&m_dsp, 0, sizeof(m_dsp));
      |                ^
      |                (void*)
../../../../../src/devices/cpu/alto2/a2ether.cpp:1310:9: error: first argument in call to 'memset' is a pointer to
      non-trivially copyable type 'struct (unnamed struct at ../../../../../src/devices/cpu/alto2/a2ether.h:50:1)'
      [-Werror,-Wnontrivial-memcall]
 1310 |         memset(&m_eth, 0, sizeof(m_eth));
      |                ^
../../../../../src/devices/cpu/alto2/a2ether.cpp:1310:9: note: explicitly cast the pointer to silence this warning
 1310 |         memset(&m_eth, 0, sizeof(m_eth));
      |                ^
      |                (void*)

**Comment by Osso13** [comment]
https://github.com/ocornut/imgui/commit/419a9ada16eb9b6d84ead4911b9c2a32820cfffb 
This seems to address the errors in 3rdparty

**Comment by MASHinfo** [comment]
I have successfully compiled MAME 0.276 with Clang 20.1 with this changes:


Add this line:
#pragma clang diagnostic ignored "-Wnontrivial-memaccess" // warning: first argument in call to 'memset' is a pointer to non-trivially copyable type

to this 6 files in 3rdparty/bgfx/3rdparty/dear-imgui/ after the Clang/GCC warnings:

imgui.cpp 		(after line 934)
imgui.h 		(after line 121)
imgui_draw.cpp 		(after line 66)
imgui_internal.h 	(after line 89)
imgui_tables.cpp 	(after line 231)
imgui_widgets.cpp 	(after line 79)


Is this working for you?

**Comment by Osso13** [comment]
Yes but it's just a workaround. It would be better to just update imgui to latest.

**Comment by cuavas** [comment]
> [ocornut/imgui@419a9ad](https://github.com/ocornut/imgui/commit/419a9ada16eb9b6d84ead4911b9c2a32820cfffb) This seems to address the errors in 3rdparty

Unfortunately that also suppresses the diagnostic in imgui.h, which means it gets suppressed in everything that uses imgui as well (currently just the imgui debugger and the bgfx renderer).

**Comment by cuavas** [comment]
All of the errors in MAME itself including the ones flagged by GCC but not by clang should be fixed as of c10ecb0941604be3cb8e5a361ad1ddd7bbd73380, with the error enabled for GCC to avoid rot creeping back in.

**Comment by cuavas** [comment]
I updated ImGui in 6c8fb3d5e69fbc82dfdc9028689c1570ec59afb9.  It was a pain to get this to work as we’re behind upstream bgfx itself, but ahead of the version of ImGui used by upstream bgfx.  The ImGui debugger seemed to work after the update.
