### ISSUE TITLE
build failure with gcc-6.0.0

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#712]
When trying to build with gcc-6.0.0 the following error occurs:
```
Compiling src/mame/machine/slikshot.cpp...
g++    -MMD -MP -MP -DPTR64=1 -DNDEBUG -DCRLF=2 -DLSB_FIRST -DUSE_SYSTEM_JPEGLIB -DUSE_SYSTEM_PORTMIDI -DUSE_SYSTEM_SQLITE -DNATIVE_DRC=drcbe_x64 -DLUA_COMPAT_ALL -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DUSE_XAUDIO2=0 -I../../../../../src/osd -I../../../../../src/emu -I../../../../../src/devices -I../../../../../src/mame -I../../../../../src/lib -I../../../../../src/lib/util -I../../../../../src/lib/netlist -I../../../../../3rdparty -I../../../../generated/mame/layout  -g -m64 --pipe -g1 -fno-omit-frame-pointer -fno-optimize-sibling-calls -Wno-deprecated-declarations -O2 -fno-strict-aliasing -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wno-unknown-pragmas -Wall -Wcast-align -Wundef -Wformat-security -Wwrite-strings -Wno-sign-compare -Wno-conversion -Wno-unused-result -Wno-array-bounds -m64 -x c++ -std=c++14 -Woverloaded-virtual -Wsuggest-override -include ../../../../linux_gcc/obj/x64/Release/emu.h -o "../../../../linux_gcc/obj/x64/Release/src/mame/machine/slikshot.o" -c "../../../../../src/mame/machine/slikshot.cpp"
../../../../../src/mame/machine/slikshot.cpp: In member function 'void itech8_state::vels_to_inters(UINT8, UINT8, UINT8, UINT16*, UINT16*, UINT16*, UINT8*)':
../../../../../src/mame/machine/slikshot.cpp:264:47: error: invalid operands of types '__gnu_cxx::__enable_if<true, double>::__type {aka double}' and 'int' to binary 'operator<<'
  *inter2 = 0x30f2e / (_27d8 + ((abs((INT8)vx) << 16) / 0x58f8c));
                                 ~~~~~~~~~~~~~~^~~~~
../../../../../src/mame/machine/slikshot.cpp:265:47: error: invalid operands of types '__gnu_cxx::__enable_if<true, double>::__type {aka double}' and 'int' to binary 'operator<<'
  inter2a = 0x30f2e / (_27d8 - ((abs((INT8)vx) << 16) / 0x58f8c));
                                 ~~~~~~~~~~~~~~^~~~~
itech.make:324: recipe for target '../../../../linux_gcc/obj/x64/Release/src/mame/machine/slikshot.o' failed
Makefile:175: recipe for target 'itech' failed
make[2]: *** [../../../../linux_gcc/obj/x64/Release/src/mame/machine/slikshot.o] Error 1
make[1]: *** [itech] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by mmicko** [comment]
try this :

inter2a = 0x30f2e / (_27d8 - ((((UINT32)abs((INT8)vx)) << 16) / 0x58f8c));

**Comment by belegdol** [comment]
Thanks, it worked. Patch attached for your convenience.
[mame-0.171-gcc6.patch.zip](https://github.com/mamedev/mame/files/170384/mame-0.171-gcc6.patch.zip)

**Comment by mmicko** [comment]
Great
