### ISSUE TITLE
Build errors with satops.hxx

### ISSUE THREAD

**Issue by drencorxeen** [mamedev/mame#3605]
I am currently trying to build on Raspbian Stretch on a Raspberry Pi 3B+ and am getting these errors.

`In file included from ../../../../../src/devices/cpu/saturn/saturn.cpp:84:0:
../../../../../src/devices/cpu/saturn/satops.hxx: In member function ‘void saturn_device::saturn_exchange(int, int, int, int)’:
../../../../../src/devices/cpu/saturn/satops.hxx:806:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void saturn_device::saturn_exchange(int left, int begin, int count, int right)
      ^~~~~~~~~~~~~
../../../../../src/devices/cpu/saturn/satops.hxx:806:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
../../../../../src/devices/cpu/saturn/satops.hxx: In member function ‘void saturn_device::saturn_copy(int, int, int, int)’:
../../../../../src/devices/cpu/saturn/satops.hxx:824:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void saturn_device::saturn_copy(int dest, int begin, int count, int src)
      ^~~~~~~~~~~~~
../../../../../src/devices/cpu/saturn/satops.hxx:824:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
../../../../../src/devices/cpu/saturn/satops.hxx: In member function ‘void saturn_device::saturn_or(int, int, int, int)’:
../../../../../src/devices/cpu/saturn/satops.hxx:1040:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void saturn_device::saturn_or(int dest, int begin, int count, int src)
      ^~~~~~~~~~~~~
../../../../../src/devices/cpu/saturn/satops.hxx:1040:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
../../../../../src/devices/cpu/saturn/satops.hxx: In member function ‘void saturn_device::saturn_and(int, int, int, int)’:
../../../../../src/devices/cpu/saturn/satops.hxx:1055:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
 void saturn_device::saturn_and(int dest, int begin, int count, int src)
      ^~~~~~~~~~~~~
../../../../../src/devices/cpu/saturn/satops.hxx:1055:6: error: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Werror=strict-overflow]
`

**Comment by Tafoid** [comment]
Try using **NOWERROR=1** and **REGENIE=1** added to your make to attempt to build through those parts.  Of course, be sure to add **-k** which continues your compile until nothing else can compile, if you don't already have this in your make.

**Comment by drencorxeen** [comment]
@Tafoid , that did help some
Now getting linking errors:

`Linking mame...
../../../../../scripts/mame_mame/liboptional.a(coco_gmc.o): In function `.LANCHOR0':
coco_gmc.cpp:(.rodata+0x12c): multiple definition of `typeinfo name for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x16c): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_gmc.o): In function `.LANCHOR0':
coco_gmc.cpp:(.rodata+0x160): multiple definition of `typeinfo for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1a0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_gmc.o): In function `.LANCHOR0':
coco_gmc.cpp:(.rodata+0x16c): multiple definition of `typeinfo name for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1ac): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_gmc.o): In function `.LANCHOR0':
coco_gmc.cpp:(.rodata+0x1a0): multiple definition of `typeinfo for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1e0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_multi.o): In function `.LANCHOR0':
coco_multi.cpp:(.rodata+0x154): multiple definition of `typeinfo name for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x16c): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_multi.o): In function `.LANCHOR0':
coco_multi.cpp:(.rodata+0x188): multiple definition of `typeinfo for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1a0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_multi.o): In function `.LANCHOR0':
coco_multi.cpp:(.rodata+0x194): multiple definition of `typeinfo name for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1ac): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_multi.o): In function `.LANCHOR0':
coco_multi.cpp:(.rodata+0x1c8): multiple definition of `typeinfo for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1e0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_orch90.o): In function `.LANCHOR0':
coco_orch90.cpp:(.rodata+0x15c): multiple definition of `typeinfo name for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x16c): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_orch90.o): In function `.LANCHOR0':
coco_orch90.cpp:(.rodata+0x190): multiple definition of `typeinfo for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1a0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_orch90.o): In function `.LANCHOR0':
coco_orch90.cpp:(.rodata+0x19c): multiple definition of `typeinfo name for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1ac): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_orch90.o): In function `.LANCHOR0':
coco_orch90.cpp:(.rodata+0x1d0): multiple definition of `typeinfo for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1e0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_rs232.o): In function `.LANCHOR0':
coco_rs232.cpp:(.rodata+0x160): multiple definition of `typeinfo name for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x16c): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_rs232.o): In function `.LANCHOR0':
coco_rs232.cpp:(.rodata+0x194): multiple definition of `typeinfo for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1a0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_rs232.o): In function `.LANCHOR0':
coco_rs232.cpp:(.rodata+0x1a0): multiple definition of `typeinfo name for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1ac): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_rs232.o): In function `.LANCHOR0':
coco_rs232.cpp:(.rodata+0x1d4): multiple definition of `typeinfo for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1e0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_ssc.o): In function `.LANCHOR0':
coco_ssc.cpp:(.rodata+0x2dc): multiple definition of `typeinfo name for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x16c): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_ssc.o): In function `.LANCHOR0':
coco_ssc.cpp:(.rodata+0x310): multiple definition of `typeinfo for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1a0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_ssc.o): In function `.LANCHOR0':
coco_ssc.cpp:(.rodata+0x31c): multiple definition of `typeinfo name for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1ac): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_ssc.o): In function `.LANCHOR0':
coco_ssc.cpp:(.rodata+0x350): multiple definition of `typeinfo for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1e0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_t4426.o): In function `.LANCHOR0':
coco_t4426.cpp:(.rodata+0x248): multiple definition of `typeinfo name for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x16c): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_t4426.o): In function `.LANCHOR0':
coco_t4426.cpp:(.rodata+0x27c): multiple definition of `typeinfo for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1a0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_t4426.o): In function `.LANCHOR0':
coco_t4426.cpp:(.rodata+0x288): multiple definition of `typeinfo name for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1ac): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_t4426.o): In function `.LANCHOR0':
coco_t4426.cpp:(.rodata+0x2bc): multiple definition of `typeinfo for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1e0): first defined here
../../../../../scripts/mame_mame/liboptional.a(dragon_fdc.o): In function `.LANCHOR0':
dragon_fdc.cpp:(.rodata+0x564): multiple definition of `typeinfo name for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x16c): first defined here
../../../../../scripts/mame_mame/liboptional.a(dragon_fdc.o): In function `.LANCHOR0':
dragon_fdc.cpp:(.rodata+0x598): multiple definition of `typeinfo for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1a0): first defined here
../../../../../scripts/mame_mame/liboptional.a(dragon_fdc.o): In function `.LANCHOR0':
dragon_fdc.cpp:(.rodata+0x5a4): multiple definition of `typeinfo name for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1ac): first defined here
../../../../../scripts/mame_mame/liboptional.a(dragon_fdc.o): In function `.LANCHOR0':
dragon_fdc.cpp:(.rodata+0x5d8): multiple definition of `typeinfo for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):coco_dcmodem.cpp:(.rodata+0x1e0): first defined here
../../../../../scripts/mame_mame/liboptional.a(mps.o): In function `.LANCHOR0':
mps.cpp:(.rodata+0x18c): multiple definition of `typeinfo name for device_finder<ss50_card_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(mpc.o):mpc.cpp:(.rodata+0x18c): first defined here
../../../../../scripts/mame_mame/liboptional.a(mps.o): In function `.LANCHOR0':
mps.cpp:(.rodata+0x1b8): multiple definition of `typeinfo for device_finder<ss50_card_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(mpc.o):mpc.cpp:(.rodata+0x1b8): first defined here
../../../../../scripts/mame_mame/liboptional.a(mps.o): In function `.LANCHOR0':
mps.cpp:(.rodata+0x1c4): multiple definition of `typeinfo name for device_finder<ss50_card_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(mpc.o):mpc.cpp:(.rodata+0x1c4): first defined here
../../../../../scripts/mame_mame/liboptional.a(mps.o): In function `.LANCHOR0':
mps.cpp:(.rodata+0x1f0): multiple definition of `typeinfo for device_finder<ss50_card_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(mpc.o):mpc.cpp:(.rodata+0x1f0): first defined here
```

**Comment by drencorxeen** [comment]
This only seems to be happening on Raspbian Jessie and Raspbian Stretch.  So far I haven't had any build issues with Ubuntu 16.04LTS 64bit or Ubuntu 18.04LTS 64bit.  

I also haven't had any issues building in the MINGW64 environment on my Windows 10 system using MSYS2.

Since Raspbian is 32bit only could that be part of the issue?

**Comment by mrgw454** [comment]
I can confirm the linking errors right at the very end.  MAME 0.197 from git (downloaded yesterday):

Linking mame...
../../../../../scripts/mame_mame/liboptional.a(coco_gmc.o):(.rodata+0x128): multiple definition of `typeinfo name for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x16c): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_gmc.o):(.rodata+0x15c): multiple definition of `typeinfo for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1a0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_gmc.o):(.rodata+0x168): multiple definition of `typeinfo name for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1ac): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_gmc.o):(.rodata+0x19c): multiple definition of `typeinfo for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1e0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_multi.o):(.rodata+0x150): multiple definition of `typeinfo name for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x16c): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_multi.o):(.rodata+0x184): multiple definition of `typeinfo for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1a0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_multi.o):(.rodata+0x190): multiple definition of `typeinfo name for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1ac): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_multi.o):(.rodata+0x1c4): multiple definition of `typeinfo for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1e0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_orch90.o):(.rodata+0x154): multiple definition of `typeinfo name for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x16c): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_orch90.o):(.rodata+0x188): multiple definition of `typeinfo for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1a0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_orch90.o):(.rodata+0x194): multiple definition of `typeinfo name for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1ac): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_orch90.o):(.rodata+0x1c8): multiple definition of `typeinfo for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1e0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_rs232.o):(.rodata+0x15c): multiple definition of `typeinfo name for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x16c): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_rs232.o):(.rodata+0x190): multiple definition of `typeinfo for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1a0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_rs232.o):(.rodata+0x19c): multiple definition of `typeinfo name for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1ac): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_rs232.o):(.rodata+0x1d0): multiple definition of `typeinfo for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1e0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_ssc.o):(.rodata+0x2dc): multiple definition of `typeinfo name for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x16c): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_ssc.o):(.rodata+0x310): multiple definition of `typeinfo for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1a0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_ssc.o):(.rodata+0x31c): multiple definition of `typeinfo name for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1ac): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_ssc.o):(.rodata+0x350): multiple definition of `typeinfo for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1e0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_t4426.o):(.rodata+0x244): multiple definition of `typeinfo name for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x16c): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_t4426.o):(.rodata+0x278): multiple definition of `typeinfo for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1a0): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_t4426.o):(.rodata+0x284): multiple definition of `typeinfo name for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1ac): first defined here
../../../../../scripts/mame_mame/liboptional.a(coco_t4426.o):(.rodata+0x2b8): multiple definition of `typeinfo for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1e0): first defined here
../../../../../scripts/mame_mame/liboptional.a(dragon_fdc.o):(.rodata+0x560): multiple definition of `typeinfo name for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x16c): first defined here
../../../../../scripts/mame_mame/liboptional.a(dragon_fdc.o):(.rodata+0x594): multiple definition of `typeinfo for device_finder<device_cococart_interface, false>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1a0): first defined here
../../../../../scripts/mame_mame/liboptional.a(dragon_fdc.o):(.rodata+0x5a0): multiple definition of `typeinfo name for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1ac): first defined here
../../../../../scripts/mame_mame/liboptional.a(dragon_fdc.o):(.rodata+0x5d4): multiple definition of `typeinfo for device_finder<device_cococart_interface, true>'
../../../../../scripts/mame_mame/liboptional.a(coco_dcmodem.o):(.rodata+0x1e0): first defined here
collect2: error: ld returned 1 exit status
mame.make:250: recipe for target '../../../../../mame' failed
make[2]: *** [../../../../../mame] Error 1
Makefile:103: recipe for target 'mame' failed
make[1]: *** [mame] Error 2
makefile:1277: recipe for target 'linux' failed
make: *** [linux] Error 2

**Comment by cuavas** [comment]
You need a newer linker.  It's legal to have the same explicit template instantiation in different compilation units - it's only illegal to duplicate it in the same compilation unit.  This became an issue with C++11, so a linker not updated to handle C++11 may not handle this correctly.

**Comment by mrgw454** [comment]
I am using an older linker on my Linux Mint 18.3 workstation:
$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.26.1
Copyright (C) 2015 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

... and a newer one on my Raspberry Pi3 (Stretch):
ld --version
GNU ld (GNU Binutils for Raspbian) 2.28
Copyright (C) 2017 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

So in my case, an older version works and a newer version fails.  I am still able to compile the 0.197 release source using ld (linker) 2.28.

**Comment by mrgw454** [comment]
Same error during compile using gcc 8.1.0 and ld 2.30.  Both are the most recent versions.

**Comment by cuavas** [comment]
File a bug against the distribution.  There's no way we can prevent the same template instantiation being created in multiple files.

**Comment by mrgw454** [comment]
I'm not sure if this is the correct thing to do, but did some research and made the following change to MAME's makefile when compiling under Raspbian for the RPi3:

LDOPTS = -z muldefs

I uncommented out that line and added the option to tell the linker to allow for multiple definitions.  This seemed to work and the resulting 'mame' executable was built and seems to run fine.  Perhaps good information to know for anyone else who wants to continue building MAME for a Raspberry Pi 3.

The build process also worked using the latest GCC 8.1.0 and binutils 2.30.  I'm still using SDL2 2.0.8.

**Comment by cuavas** [comment]
File a bug against the linker. We don't have this problem on Visual Studio, MinGW, desktop Linux distributions, or macOS. We can't work around broken tools all the time.

**Comment by galibert** [comment]
You're not understanding these lines.

They mean that device_finder<device_cococart_interface, false> and
device_finder<device_cococart_interface, true>, or in other words
optional_device<device_cococart_interface> and
required_device<device_cococart_interface>, should be intantiated in that
object file.

  OG.
