### PR TITLE
evdev input module

### PR DESCRIPTION
**Pull request by Cauren**
First run at an input module for the event device interface supported by Linux (and, IIRC, FreeBSD).

Current state:  It _works_, but has minimal error handling and may not be as efficient as it could be (in particular, there may be an unsatisfying number of context switches needed during poll that may be improved by moving reading the devices onto a separate thread).  It's mostly submited in its current state for feedback/critique by the dev team.

Raison d'être:  SDL input device handling is portable but pretty threadbare and has unacceptable limitations (mice have only exactly two supported axes, joysticks are expected to have a set number of absolute axes only, and so on).  Evdev exposes _all_ controls of all compliant USB HID, with better identification of buttons and axes, as well as a number of non-USB devices, in a well-defined format.

Tested with a number of mice, keyboards, analog sticks and adapter boards (mostly Ultimarc's)

### CODE REVIEW

**Comment by Cauren** [comment]
... not sure why the clang build failed?  Or why the gcc build was canceled.

FWIW this builds with no issues on Linux/GCC 10.2.1.

**Comment by startaq** [comment]
The GCC build was cancelled because the clang build failed. The error can be seen in the logs (click on 'Details'):

```
../../../../../src/osd/modules/input/input_evdev.cpp:622:75: error: use of undeclared identifier 'SDLOPTION_KEYBINDEX'
                input_setup(machine, "Keyboard", DEVICE_CLASS_KEYBOARD, EVDEV_KEYBOARD, SDLOPTION_KEYBINDEX);
                                                                                        ^
../../../../../src/osd/modules/input/input_evdev.cpp:636:66: error: use of undeclared identifier 'SDLOPTION_MOUSEINDEX'
                input_setup(machine, "Mouse", DEVICE_CLASS_MOUSE, EVDEV_MOUSE, SDLOPTION_MOUSEINDEX);
                                                                               ^
../../../../../src/osd/modules/input/input_evdev.cpp:649:75: error: use of undeclared identifier 'SDLOPTION_JOYINDEX'
                input_setup(machine, "Joystick", DEVICE_CLASS_JOYSTICK, EVDEV_JOYSTICK, SDLOPTION_JOYINDEX);
                                                                                        ^
3 errors generated.
make[2]: *** [osd_sdl.make:992: ../../../../linux_clang/obj/x64/Release/osd_sdl/src/osd/modules/input/input_evdev.o] Error 1
make[1]: *** [Makefile:19: osd_sdl] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by Cauren** [comment]
> ../../../../../src/osd/modules/input/input_evdev.cpp:649:75: error: use of undeclared identifier 'SDLOPTION_JOYINDEX'
>                 input_setup(machine, "Joystick", DEVICE_CLASS_JOYSTICK, EVDEV_JOYSTICK, SDLOPTION_JOYINDEX);

Aha!  The options were removed two weeks ago in commit b80b4066bfefb4e19c9a2d8c30b511bee947b921 because they weren't actually useful for SDL just as I started using them because they _were_ useful for evdev!

I hadn't noticed HEAD changed between the start and end of my doing the patch.

Now an interesting design question:  should I reintroduce analogous options (-joy_indexX) or a single option that takes a comma separated list of mappings instead?  My first inclination would be the latter -- the only reason I used the existing SDL options was because... they were existing.  :-)

**Comment by Cauren** [comment]
I think I answered my own question indirectly -- evdev input actually has _no_ dependency on SDL at all except for overloading those options so it makes no sense to reintroduce a dependency.

I'll introduce a USE_EVDEV flag instead, and create a specific option for this rather than rely on SDLMAME_LINUX

**Comment by Cauren** [comment]
(Quick fix because I realized too late that this wouldn't build under not-linux if USE_EVDEV was left undefined)

**Comment by Cauren** [comment]
Call me an optimist, but I'm _pretty_ sure the Windows build breaking in the lua tree isn't mine.  :-)

**Comment by Tafoid** [comment]
> Call me an optimist, but I'm _pretty_ sure the Windows build breaking in the lua tree isn't mine. :-)

I see this.  A file missing?

```
 ../../../../../src/osd/modules/input/input_evdev.cpp:14:6: error: "USE_EVDEV" is not defined, evaluates to 0 [-Werror=undef]
   14 | #if (USE_EVDEV)
      |      ^~~~~~~~~
Compiling src/devices/bus/adam/exp.cpp...
cc1plus.exe: all warnings being treated as errors
make[2]: *** [osd_windows.make:1146: ../../../../mingw-gcc/obj/x64/Release/osd_windows/src/osd/modules/input/input_evdev.o] Error 1
make[1]: *** [Makefile:19: osd_windows] Error 2
make[1]: *** Waiting for unfinished jobs....

```

**Comment by Cauren** [comment]
> I see this. A file missing?
> 
> ```
>  ../../../../../src/osd/modules/input/input_evdev.cpp:14:6: error: "USE_EVDEV" is not defined, evaluates to 0 [-Werror=undef]
>    14 | #if (USE_EVDEV)
>       |      ^~~~~~~~~

...  _I_ don't see it, odd!  The output from builds looks truncated to me for some reason, and I don't have a Windows box handy to debug.

Ah!  I set USE_EVDEV for all SDL builds but don't guard against not-SDL builds.  Easy fix.

**Comment by cuavas** [comment]
You shouldn’t be introducing command line options for mapping the input device indices at all.  The proper way is to expose stable IDs so they can be remapped using controller configuration files – see here: https://docs.mamedev.org/advanced/devicemap.html

File: src/osd/sdl/osdsdl.h [hunk 1]
```diff
@@ -32,6 +32,13 @@
 #define SDLOPTION_LIGHTGUNINDEX         "lightgun_index"
 #endif
 
+#if (USE_EVDEV)
+#define SDLOPTION_KEYBOARD_DEV          "keyboard_dev"
+#define SDLOPTION_JOYSTICK_DEV          "joystick_dev"
+#define SDLOPTION_MOUSE_DEV             "mouse_dev"
+#define SDLOPTION_LIGHTGUN_DEV          "lightgun_dev"
+#endif
+
```
Comment (cuavas) [inline src/osd/sdl/osdsdl.h:41]: This isn’t the direction we’re taking for things like this – please ensure you’re exposing predictable IDs for devices so they can be remapped using controller configuration files.

File: src/osd/sdl/sdlmain.cpp [hunk 2]
```diff
@@ -105,6 +105,14 @@ const options_entry sdl_options::s_option_entries[] =
...
 	{ SDLOPTION_SIXAXIS,                     "0",            core_options::option_type::BOOLEAN,    "use special handling for PS3 Sixaxis controllers" },
 
+#if (USE_EVDEV)
+	{ nullptr,                              nullptr,         core_options::option_type::HEADER,     "SDL EVENT DEVICE MAPPING" },
+	{ SDLOPTION_KEYBOARD_DEV,               OSDOPTVAL_AUTO,  core_options::option_type::STRING,     "evdev devices to map as keyboards" },
+	{ SDLOPTION_JOYSTICK_DEV,               OSDOPTVAL_AUTO,  core_options::option_type::STRING,     "evdev devices to map as joysticks" },
+	{ SDLOPTION_MOUSE_DEV,                  OSDOPTVAL_AUTO,  core_options::option_type::STRING,     "evdev devices to map as mice" },
+	{ SDLOPTION_LIGHTGUN_DEV,               OSDOPTVAL_AUTO,  core_options::option_type::STRING,     "evdev devices to map as lightguns" },
+#endif
+
```
Comment (cuavas) [inline src/osd/sdl/sdlmain.cpp:115]: Same here – this is the wrong solution.

File: src/osd/modules/input/input_evdev.cpp [hunk 3]
```diff
@@ -0,0 +1,713 @@
...
+//  input_evdev.cpp - Linux evdev input module
+//
+//  SDLMAME by Olivier Galibert and R. Belmont
+//
+//============================================================
+
+#include "input_module.h"
+#include "modules/osdmodule.h"
+
+#if defined(SDLMAME_SDL2) && (USE_EVDEV)
```
Comment (cuavas) [inline src/osd/modules/input/input_evdev.cpp:14]: Is this actually dependent on SDL at all (e.g. using SDL to get a window reference or something), or could it work with a different event loop?  It shouldn’t be checking for SDL if it doesn’t depend on it.

File: src/osd/modules/input/input_evdev.cpp [hunk 4]
```diff
@@ -0,0 +1,713 @@
...
+	{ ABS_GAS,		ITEM_ID_ADD_ABSOLUTE2,	"GAS" },
+	{ ABS_BRAKE,		ITEM_ID_ADD_ABSOLUTE3,	"BRAKE" },
+	{ ABS_HAT0X,		ITEM_ID_ADD_ABSOLUTE4,	"HAT1 X" },
+	{ ABS_HAT0Y,		ITEM_ID_ADD_ABSOLUTE5,	"HAT1 Y" },
+	{ ABS_HAT1X,		ITEM_ID_ADD_ABSOLUTE6,	"HAT2 X" },
+	{ ABS_HAT1Y,		ITEM_ID_ADD_ABSOLUTE7,	"HAT2 Y" },
+	{ ABS_HAT2X,		ITEM_ID_ADD_ABSOLUTE8,	"HAT3 X" },
+	{ ABS_HAT2Y,		ITEM_ID_ADD_ABSOLUTE9,	"HAT3 Y" },
+	{ ABS_HAT3X,		ITEM_ID_ADD_ABSOLUTE10,	"HAT4 X" },
+	{ ABS_HAT3Y,		ITEM_ID_ADD_ABSOLUTE11,	"HAT4 Y" },
```
Comment (cuavas) [inline src/osd/modules/input/input_evdev.cpp:250]: People are going to expect hat switches to map to a set of digital inputs – you’re going to have to have to convert the “axis” value.

File: src/osd/modules/input/input_evdev.cpp [hunk 5]
```diff
@@ -0,0 +1,713 @@
...
+enum device_type {
+	EVDEV_NONE,
+	EVDEV_KEYBOARD,
+	EVDEV_MOUSE,
+	EVDEV_JOYSTICK,
+	EVDEV_GENERIC,
+};
+
+
+#define OCTETS_FOR(n) ((n+7)>>3)
```
Comment (cuavas) [inline src/osd/modules/input/input_evdev.cpp:268]: Please don’t use macros unnecessarily – you can use `constexpr` functions for things like this.

File: src/osd/modules/input/input_evdev.cpp [hunk 6]
```diff
@@ -0,0 +1,713 @@
...
+				if(absaxis_map[mapi].evdev_id == i) {
+					if(fd >= 0)
+						ioctl(fd, EVIOCGABS(i), &absaxis[i].absinfo);
+					device()->add_item(absaxis_map[mapi].name, absaxis_map[mapi].mame_id,
+						generic_axis_get_state<int32_t>, &absaxis[i].normalized);
+				}
+			}
+	}
+
+	void poll(void) override
```
Comment (cuavas) [inline src/osd/modules/input/input_evdev.cpp:377]: We don’t put the `void` in the parameter list for functions with no arguments in MAME.

File: src/osd/modules/input/input_evdev.cpp [hunk 7]
```diff
@@ -0,0 +1,713 @@
...
+	{
+		static input_event ie[256]; // try to consume as many as possible at once
```
Comment (cuavas) [inline src/osd/modules/input/input_evdev.cpp:379]: Having a function static like this is generally a bad sign.

File: src/osd/modules/input/input_evdev.cpp [hunk 8]
```diff
@@ -0,0 +1,713 @@
...
+				}
+			}
+		}
+	}
+
+	void reset(void) override
+	{
+		memset(keystate, 0, KEY_MAX);
+		memset(relaxis, 0, REL_MAX*sizeof(int32_t));
+		memset(absaxis, 0, ABS_MAX*sizeof(absaxis[0]));
```
Comment (cuavas) [inline src/osd/modules/input/input_evdev.cpp:412]: Please use `std::fill` - it’s safer.

File: src/osd/modules/input/input_evdev.cpp [hunk 9]
```diff
@@ -0,0 +1,713 @@
...
+#define MAX_EVDEV_DEVICES 64
+
+class evdev_input
+{
+private:
+	bool initialized;
+
+public:
+	int  devinput;
+	evdev_device_info dev[MAX_EVDEV_DEVICES]; // 640k should be enough for anyone
```
Comment (cuavas) [inline src/osd/modules/input/input_evdev.cpp:425]: Why not use s vector, or if the items can’t be moved, a vector of smart pointers or a list?

File: src/osd/modules/input/input_evdev.cpp [hunk 10]
```diff
@@ -0,0 +1,713 @@
...
+		}
+
+		DIR* idir = fdopendir(devinput);
+		while(idir) {
+			dirent* de = readdir(idir);
+			if(!de)
+				break;
+			if(strncmp(de->d_name, "event", 5))
+				continue;
+			int dnum = atoi(de->d_name+5);
```
Comment (cuavas) [inline src/osd/modules/input/input_evdev.cpp:457]: `atoi` depends on the global locale – you should avoid it if possible.

File: src/osd/modules/input/input_evdev.cpp [hunk 11]
```diff
@@ -0,0 +1,713 @@
...
+				osd_printf_verbose("evdev: unable to open de->d_name: %s\n", strerror(errno));
+				continue;
+			}
+			input_id iid;
+			if(ioctl(ed, EVIOCGID, &iid)<0) {
+				osd_printf_verbose("evdev: event%d doesn't looks usable\n", dnum);
+				close(ed);
+				continue;
+			} else
+				snprintf(dev[dnum].id, 32, "%hu:%04hx:%04hx", iid.bustype, iid.vendor, iid.product);
```
Comment (cuavas) [inline src/osd/modules/input/input_evdev.cpp:479]: This isn’t going to produce unique IDs when someone has two similar devices connected (e.g. two Logitech Dual Action gamepads).  Can you expose the device serial number, or failing that, the datalink address for Bluetooth devices, or something derived from bus topology for USB devices?

Also, you should use `util::string_format` as it’s type-safe etc.

File: src/osd/modules/input/input_evdev.cpp (hunk 4 above)
Comment (Cauren) [reply src/osd/modules/input/input_evdev.cpp:250]: Really?  It's fine with me in principle but I'd have expected hats to behave as axes not buttons (it turns out that I never used a device with a hat with mame so I suppose I don't start with an _actual_ expectation).

My reasoning: a hat behaves like a joystick because the directions are physically mutually excluded (you can never have "left" and "right" simultaneously, only either or none) so at first glance it makes no sense to map those to buttons (which you'd expect can be triggered in any combination).

If that's unconvincing, would it make sense to make that a configurable options instead?

File: src/osd/modules/input/input_evdev.cpp (hunk 5 above)
Comment (Cauren) [reply src/osd/modules/input/input_evdev.cpp:268]: Gotcha.

File: src/osd/sdl/osdsdl.h (hunk 1 above)
Comment (Cauren) [reply src/osd/sdl/osdsdl.h:41]: Gotcha.  First attempt at messing with the mame code so I'm not all that aware of "this is what we're aiming for today" as opposed to modeling on "this is how we did things yesteryear".  :-)

I'll axe the mapping options entirely and concentrate on stable unique IDs instead.

File: src/osd/modules/input/input_evdev.cpp (hunk 3 above)
Comment (Cauren) [reply src/osd/modules/input/input_evdev.cpp:14]: (as above)

Comment (Cauren) [reply src/osd/modules/input/input_evdev.cpp:14]: It isn't, in any way.  In fact, that's the reason why I initially went with just USE_EVDEV.

I added that because I saw no obvious way to add options to Linux builds only beyond relying on SDL being the only Linux target right now, but that becomes entirely moot if we remove the options anyways.

So then the question becomes:  where do I _correctly_ add USE_EVDEV to the defines?  Directly as such in the top level makefile?

File: src/osd/sdl/sdlmain.cpp (hunk 2 above)
Comment (Cauren) [reply src/osd/sdl/sdlmain.cpp:115]: (As above, fully agreed)

File: src/osd/modules/input/input_evdev.cpp (hunk 7 above)
Comment (Cauren) [reply src/osd/modules/input/input_evdev.cpp:379]: I wanted to avoid stack trashing on a function that is called really often; the actual lifetime of the buffer is exactly the life of the function call so making it local won't break things.

That said, my first obvious improvement is to move the read()s away from poll() entirely and have a thread that does a select()/read() asynchronously (and then only when there's an actual event) so it's kinda moot.

... which raises the question on whether this is a reasonable thing to do at all given your current architecture, and if it is what the "proper" way of doing it is.  I didn't find a good venue where I could ask questions like this to the dev team short of submitting WIP.  :-D

File: src/osd/modules/input/input_evdev.cpp (hunk 8 above)
Comment (Cauren) [reply src/osd/modules/input/input_evdev.cpp:412]: Gotcha.

File: src/osd/modules/input/input_evdev.cpp (hunk 9 above)
Comment (Cauren) [reply src/osd/modules/input/input_evdev.cpp:425]: You can never really scrub away the old dinosaur C programmer bad habits away.

Yeah, this absolutely should be a vector which also does away neatly with the silly arbitrary limit.

File: src/osd/modules/input/input_evdev.cpp (hunk 10 above)
Comment (Cauren) [reply src/osd/modules/input/input_evdev.cpp:457]: Is there a usable non-locale dependent function I can use instead?  I doubt I'm the only one finding myself gaving to decoding decimal from ascii.

File: src/osd/modules/input/input_evdev.cpp (hunk 6 above)
Comment (Cauren) [reply src/osd/modules/input/input_evdev.cpp:377]: Gotcha.

**Comment by Cauren** [comment]
> You shouldn’t be introducing command line options for mapping the input device indices at all.

This leads me to two process questions:  I'm going to rip the options out in favor of using complete bus addresses as ID, and do the assorted improvements below; should I push again and let CI do it's thang or is there some other way you'd prefer?

Question two:  would you rather I wait until I have the improved code with select() in a thread or should that be considered a different thing and you'd rather have the initial version fully okayed first?

**Comment by Cauren** [comment]
... question 3:  My usual workflow has me commit often with small self-contained changes rather than one big commit with omnibus rewrites; should I squash commits when I push or are you okay with more small commits?

File: src/osd/sdl/osdsdl.h (hunk 1 above)
Comment (Cauren) [reply src/osd/sdl/osdsdl.h:41]: There remains an issue with lightguns, however, and no obvious way to fix it without introducing a command-line option that I can think of: they present themselves to the OS as mice.  Short of a way to override that, they'll show up as such.

On the other hand, evdev doesn't _care_ about what is a mouse or whatever.  As far as it's concerned everything is just a device with an arbitrary number of buttons and axes and it'll happily allow you to use it however you want -- a "keyboard" is just a joystick with no axes and lots of buttons.  :-)

The only reason I care at all in the code is because _Mame_ makes a distinction in the UI, so I guess from the available events whether it should show up as a "Keyboard", "Mouse" or "Joystick" -- but I can't guess "Lightgun".

File: src/osd/modules/input/input_evdev.cpp (hunk 10 above)
Comment (Cauren) [reply src/osd/modules/input/input_evdev.cpp:457]: (Not an issue, the refactor eleminated all atoi() calls anyways)

**Comment by Cauren** [comment]
(Please don't start CI just yet)

**Comment by Cauren** [comment]
With this set of commits, I would call the module "version 1".

There are open questions about mapping of hats and lightgun support that may need further work (see open comments above) but its current state is "functional and useful".

File: src/osd/modules/input/input_evdev.cpp (hunk 7 above)
Comment (Cauren) [reply src/osd/modules/input/input_evdev.cpp]: This is now moot with the new worker thread

File: src/osd/sdl/osdsdl.h (hunk 1 above)
Comment (galibert) [reply src/osd/sdl/osdsdl.h]: The reasons would be better automatic mappings on analog axes (we really need to work on that).  Wheels and flight controls are not really compatible, usage-wise :-)

File: src/osd/modules/input/input_evdev.cpp (hunk 4 above)
Comment (galibert) [reply src/osd/modules/input/input_evdev.cpp:244]: I thought our input code expected joysticks to show up as digital inputs too in any case?

Comment (cuavas) [reply src/osd/modules/input/input_evdev.cpp:244]: > I thought our input code expected joysticks to show up as digital inputs too in any case?

No, turning absolute axis values into “digital” toggle values happens in the core (look for `read_as_switch` members in src/emu/inputdev.cpp specifically).  The input module just reports axis values.

File: src/osd/sdl/osdsdl.h (hunk 1 above)
Comment (cuavas) [reply src/osd/sdl/osdsdl.h]: Lightgun and mouse inputs are logically different though:
* A lightgun (or a lightpen, or a digitiser tablet for that matter) gives you pointer acquired (gun pointed at screen, or pen in proximity), absolute X/Y locations (referenced to the screen), and some additional action controls (gun triggers, pen pressure, pen angle).
* A mouse or trackball gives relative X/Y movement, and additional button state.

Now in practice, PC lightguns often produce pointer movement, and digitiser tablets often provide relative movement as a fallback in case the OS doesn’t have suitable drivers.  As a result, in MAME, a lightgun peripheral may end up appearing as a mouse *and* a lightgun.

The separation between device classes is useful for a few reasons. As well as automatic input assignments that @galibert mentioned, you can specify different modules to handle different classes of device.  For example, suppose you’re using Windows on a notebook computer with a precision touchpad.  This won’t produce RawInput mouse events, so you may want to switch your mouse provider to the one that uses Win32 window messages, while still using the default RawInput keyboard provider.

**Comment by galibert** [comment]
You have touchscreens too.  I'll check tomorrow what mine is seen as on the evdev side (xorg makes it control the mouse).

File: src/osd/modules/input/input_evdev.cpp [hunk 12]
```diff
@@ -0,0 +1,745 @@
...
+
+			dev.emplace_back();
+			evdev_device_info& device = dev.back(); // C++17 would return back() from emplace_back()
+			
+			device.name = namebuf;
+			device.id = de->d_name;
+
+			std::fill(std::begin(device.buttons), std::end(device.buttons), 0);
+			std::fill(std::begin(device.relaxes), std::end(device.relaxes), 0);
+			std::fill(std::begin(device.absaxes), std::end(device.absaxes), 0);
```
Comment (cuavas) [inline src/osd/modules/input/input_evdev.cpp:574]: You know, MAME *is* C++17.  But wouldn’t it be even better to encapsulate the initialisation in the device constructor?

**Review by cuavas — COMMENTED** [review]
You’re going to need some kind of heuristic to detect what should appear as a lightgun vs a mouse.  Do you have something like an Aimtrak gun for testing purposes?  Unfortunately I don’t, so I don’t know what they actually look like from evdev’s point of view.  I can find out what a digitiser tablet looks like, but I’d need to write some code to do that.

**Comment by nadenislamarre** [comment]
could this patch help https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulators/mame/005-lightgun-udev-driver.patch ?
