### ISSUE TITLE
luaL_Buffer_52 {aka struct luaL_Buffer_52}' has no member named 'initb'

### ISSUE THREAD

**Issue by livingsilver94** [mamedev/mame#2648]
I'm compiling  v0.189 on Solus with every possible 3rd party lib as system lib.
Bundled sol library's `luaL_Buffer_52` does not contain fields that `luaengine.cpp` is using. I have compile errors on `luaengine.cpp` on line 56:

`../../../../../src/frontend/mame/luaengine.cpp: In constructor 'sol::buffer::buffer(int, lua_State*)':
../../../../../src/frontend/mame/luaengine.cpp:56:22: error: 'luaL_Buffer_52 {aka struct luaL_Buffer_52}' has no member named 'initb'
    if(buff.b != buff.initb)`

`../../../../../src/frontend/mame/luaengine.cpp: In destructor 'sol::buffer::~buffer()':
../../../../../src/frontend/mame/luaengine.cpp:64:24: error: 'luaL_Buffer_52 {aka struct luaL_Buffer_52}' has no member named 'L'
    lua_State *L = buff.L;`

In fact, that's the `luaL_Buffer_52` code:

```
typedef struct luaL_Buffer_52 {
    luaL_Buffer b; /* make incorrect code crash! */
    char *ptr;
    size_t nelems;
    size_t capacity;
    lua_State *L2;
} luaL_Buffer_52;
```

Am I doing something wrong? Thank you!

**Comment by cracyc** [comment]
luaL_Buffer_52 is only included if lua version is 5.1.  luaengine is only expected to work on 5.3.

**Comment by livingsilver94** [comment]
OK so it's a Lua version issue. Solus in fact currently provides Lua 5.1.5.
Thank you for your assistance, I wasn't able to find where it's stated that Lua 5.3 is needed.

**Comment by cracyc** [comment]
You could probably get it to build with minor changes but many of the included plugins use features (especially bit operators) added in 5.3.

**Comment by livingsilver94** [comment]
I've already been able to pass a `luaopen_bit32() not declared` issue using `luajit` but then those other errors appeared. I don't think it's worth the pain to patch stuff. Besides, Lua 5.1 is really old.
