### ISSUE TITLE
macOS build problem: constraints not satisfied

### ISSUE THREAD

**Issue by 0-wiz-0** [mamedev/mame#15850]
### MAME version

0.289

### System information

Darwin 23.6.0/aarch64
clang-15.0.0

### INI configuration details

```INI
n/a
```

### Emulated system/software

n/a

### Incorrect behaviour

After updating the mame package in pkgsrc from 0.288 to 0.289, we see a [new build failure on macOS](https://reports.pkgci.org/Darwin/14.5/arm64/20260805T051518Z/mame-0.289/build.log) in the automated package builder:
```
In file included from ../../../../../src/mame/access/acvirus.cpp:76:
../../../../../src/emu/emupal.h:281:41: error: invalid reference to function 'device_delegate_base': constraints not satisfied
                : palette_device(mconfig, tag, owner, init_delegate(*this, FUNC(palette_device::palette_init_rgb_444_proms)), entries)
                                                      ^
In file included from ../../../../../src/mame/access/acvirus.cpp:64:
In file included from ../../../../../src/emu/emu.h:47:
../../../../../src/emu/devdelegate.h:193:99: note: because substituted constraint expression is ill-formed: value of type '<dependent type>' is not contextually convertible to 'bool'
        device_delegate_base(T &object, ReturnType (D::*funcptr)(Params...), char const *name) requires (is_related_device<D, T>::value)
                                                                                                         ^
```

### Expected behaviour

Build succeeds.

**Comment by cuavas** [comment]
This is a bug in the version of clang you’re using.  You’ll need to update to a newer version of clang.
