### ISSUE TITLE
dont build on BE linux 

### ISSUE THREAD

**Issue by tlosm** [mamedev/mame#1995]
i have this issue when try to build on BE os target linux ubuntu 16.10 
selected the the make configs : 
TARGET = mame BIGENDIAN = 1 TARGETOS = linux

issue:
In file included from ../../../../../3rdparty/bgfx/examples/common/bgfx_utils.cpp:29:0:
../../../../../3rdparty/bgfx/3rdparty/tinyexr/tinyexr.h:796:52: error: "MINIZ_X86_OR_X64_CPU" is not defined [-Werror=undef]
 #if (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__) || MINIZ_X86_OR_X64_CPU
                                                    ^~~~~~~~~~~~~~~~~~~~
../../../../../3rdparty/bgfx/3rdparty/tinyexr/tinyexr.h:802:5: error: "MINIZ_X86_OR_X64_CPU" is not defined [-Werror=undef]
 #if MINIZ_X86_OR_X64_CPU
     ^~~~~~~~~~~~~~~~~~~~
In file included from ../../../../../3rdparty/bgfx/examples/common/bgfx_utils.cpp:29:0:
../../../../../3rdparty/bgfx/3rdparty/tinyexr/tinyexr.h:1832:5: error: "MINIZ_USE_UNALIGNED_LOADS_AND_STORES" is not defined [-Werror=undef]
 #if MINIZ_USE_UNALIGNED_LOADS_AND_STORES && MINIZ_LITTLE_ENDIAN
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../../../3rdparty/bgfx/3rdparty/tinyexr/tinyexr.h:2787:5: error: "MINIZ_USE_UNALIGNED_LOADS_AND_STORES" is not defined [-Werror=undef]

seams the big endian is not recognized and compiler try to build as x86 only

thanks
Luigi

**Comment by Robbbert** [comment]
Is this still a problem?

**Comment by Robbbert** [comment]
Nothing heard; closing.
