### PR TITLE
bug: gcc-12.3.0 identifies these as uninitialized/maybe-uninitialized

### PR DESCRIPTION
**Pull request by joshuashaffer**
Three lines to make it compile with g++ 12.3.0 with -Werror=uninitialized and -Werror=maybe-uninitialized (default flags).

### CODE REVIEW

**Comment by holub** [comment]
Hi @joshuashaffer. You are fixing external libraries which MAME consumes AS IS. The best place for this fix would be lib's repo, then upgrade them entirely here.

**Comment by joshuashaffer** [comment]
What would be the correct repository?

**Comment by holub** [comment]
> What would be the correct repository?

Sorry. I didn't pay too much attention, I was thinking about 3rdparty libs.

**Comment by cuavas** [comment]
The changes don’t match the description of the pull request.  For example the change to server_http_impl.hpp *moves a member from one class to another*.  This looks a lot like using so-called “artificial intelligence” to mess with things you don’t understand and waste everyone’s time.

**Comment by joshuashaffer** [comment]
Huh what?

I was getting compilation errors with Werror settings with my version of g++, fixed it so the values were initiated. 

That's all this does. It's three lines.

**Comment by joshuashaffer** [comment]
> The changes don’t match the description of the pull request.  For example the change to server_http_impl.hpp *moves a member from one class to another*.  This looks a lot like using so-called “artificial intelligence” to mess with things you don’t understand and waste everyone’s time.

It absolutely matches what I wrote.
@cuavas @holub

**Comment by rb6502** [comment]
Only 1 of the 3 changes is even in the neighborhood of initialization.  The other two are pointless churn.  Can you please copy-paste the compile error you were getting with the stock code?

**Comment by happppp** [comment]
http: did not check, but looking at the source change AI suggested, the compiler warning is bogus.
prandom: looks like a bogus compiler warning.
parray: If the warning is not bogus either, I think it's allocating uninitialized on purpose.

The netlist compiler warnings on GCC 15, a big wall of text:
```
GCC 15.2.0 detected
Compiling src/lib/netlist/analog/nld_bjt.cpp...
Compiling src/lib/netlist/analog/nld_mosfet.cpp...
Compiling src/lib/netlist/analog/nld_opamps.cpp...
Compiling src/lib/netlist/analog/nld_switches.cpp...
Compiling src/lib/netlist/analog/nlid_fourterm.cpp...
Compiling src/lib/netlist/analog/nlid_twoterm.cpp...
Compiling src/lib/netlist/devices/net_lib.cpp...
Compiling src/lib/netlist/devices/nld_4053.cpp...
Compiling src/lib/netlist/devices/nld_4066.cpp...
Compiling src/lib/netlist/devices/nld_4316.cpp...
Compiling src/lib/netlist/devices/nld_74123.cpp...
Compiling src/lib/netlist/devices/nld_74ls629.cpp...
Compiling src/lib/netlist/devices/nld_mm5837.cpp...
Compiling src/lib/netlist/devices/nld_ne555.cpp...
Compiling src/lib/netlist/devices/nld_r2r_dac.cpp...
Compiling src/lib/netlist/devices/nld_schmitt.cpp...
Compiling src/lib/netlist/devices/nld_system.cpp...
Compiling src/lib/netlist/devices/nlid_proxy.cpp...
Compiling src/lib/netlist/nl_base.cpp...
Compiling src/lib/netlist/nl_setup.cpp...
Compiling src/lib/netlist/solver/nld_matrix_solver.cpp...
Compiling src/lib/netlist/solver/nld_solver.cpp...
In file included from ../../../../../src/lib/netlist/devices/nlid_system.h:13,
                 from ../../../../../src/lib/netlist/devices/nld_system.cpp:9:
../../../../../src/lib/netlist/plib/prandom.h: In instantiation of 'plib::normal_distribution_t<FT>::normal_distribution_t(FT) [with FT = double]':
../../../../../src/lib/netlist/devices/nlid_system.h:562:5:   required from 'netlist::devices::nld_sys_noise<E, D>::nld_sys_noise(netlist::device_t::constructor_param_t) [with E = plib::mersenne_twister_t<long long unsigned int, 64, 312, 156, 31, 13043109905998158313, 29, 6148914691236517205, 17, 8202884508482404352, 37, 18444473444759240704, 43, 6364136223846793005>; D = plib::normal_distribution_t; netlist::device_t::constructor_param_t = const netlist::core_device_data_t&]'
  562 |                 , m_dis(*this, "m_dis",m_sigma())
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Dev/MAME/git_mame/src/lib/netlist/plib/palloc.h:569:12:   required from 'T* plib::detail::alloc(ARENA&, Args&& ...) [with T = netlist::devices::nld_sys_noise<plib::mersenne_twister_t<long long unsigned int, 64, 312, 156, 31, 13043109905998158313, 29, 6148914691236517205, 17, 8202884508482404352, 37, 18444473444759240704, 43, 6364136223846793005>, plib::normal_distribution_t>; long long unsigned int ALIGN = 0; ARENA = plib::mempool_arena<plib::aligned_arena<>, 16>; Args = {netlist::core_device_data_t}]'
  569 |                                 return new (mem) T(std::forward<Args>(args)...);
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Dev/MAME/git_mame/src/lib/netlist/plib/palloc.h:641:38:   required from 'typename ARENA::unique_ptr<T, ALIGN> plib::make_unique(ARENA&, Args&& ...) [with T = netlist::devices::nld_sys_noise<mersenne_twister_t<long long unsigned int, 64, 312, 156, 31, 13043109905998158313, 29, 6148914691236517205, 17, 8202884508482404352, 37, 18444473444759240704, 43, 6364136223846793005>, normal_distribution_t>; ARENA = mempool_arena<aligned_arena<>, 16>; long long unsigned int ALIGN = 0; Args = {netlist::core_device_data_t}; typename ARENA::unique_ptr<T, ALIGN> = std::unique_ptr<netlist::devices::nld_sys_noise<mersenne_twister_t<long long unsigned int, 64, 312, 156, 31, 13043109905998158313, 29, 6148914691236517205, 17, 8202884508482404352, 37, 18444473444759240704, 43, 6364136223846793005>, normal_distribution_t>, arena_deleter<mempool_arena<aligned_arena<>, 16>, netlist::devices::nld_sys_noise<mersenne_twister_t<long long unsigned int, 64, 312, 156, 31, 13043109905998158313, 29, 6148914691236517205, 17, 8202884508482404352, 37, 18444473444759240704, 43, 6364136223846793005>, normal_distribution_t>, 16> >]'
  641 |                 auto *mem = detail::alloc<T, ALIGN>(arena, std::forward<Args>(args)...);
      |                             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Dev/MAME/git_mame/src/lib/netlist/nl_factory.h:140:31:   required from 'netlist::factory::element_t::dev_uptr netlist::factory::device_element_t<C, Args>::make_device(netlist::device_arena&, netlist::netlist_state_t&, const pstring&, std::tuple<_Elements ...>&, std::index_sequence<_Ind ...>) [with long long unsigned int ...Is = {}; C = netlist::devices::nld_sys_noise<plib::mersenne_twister_t<long long unsigned int, 64, 312, 156, 31, 13043109905998158313, 29, 6148914691236517205, 17, 8202884508482404352, 37, 18444473444759240704, 43, 6364136223846793005>, plib::normal_distribution_t>; Args = {}; netlist::factory::element_t::dev_uptr = std::unique_ptr<netlist::core_device_t, plib::arena_deleter<plib::mempool_arena<plib::aligned_arena<>, 16>, netlist::core_device_t, 16> >; netlist::device_arena = plib::mempool_arena<plib::aligned_arena<>, 16>; pstring = pstring_t<putf_traits<1, char> >; std::index_sequence<_Ind ...> = std::integer_sequence<long long unsigned int>]'
  140 |                         return plib::make_unique<C>(
      |                                ~~~~~~~~~~~~~~~~~~~~^
  141 |                                 pool, constructor_data_t{anetlist, name},
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  142 |                                 std::forward<Args>(std::get<Is>(args))...);
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Dev/MAME/git_mame/src/lib/netlist/nl_factory.h:148:22:   required from 'netlist::factory::element_t::dev_uptr netlist::factory::device_element_t<C, Args>::make_device(netlist::device_arena&, netlist::netlist_state_t&, const pstring&, std::tuple<_Elements ...>&) [with C = netlist::devices::nld_sys_noise<plib::mersenne_twister_t<long long unsigned int, 64, 312, 156, 31, 13043109905998158313, 29, 6148914691236517205, 17, 8202884508482404352, 37, 18444473444759240704, 43, 6364136223846793005>, plib::normal_distribution_t>; Args = {}; netlist::factory::element_t::dev_uptr = std::unique_ptr<netlist::core_device_t, plib::arena_deleter<plib::mempool_arena<plib::aligned_arena<>, 16>, netlist::core_device_t, 16> >; netlist::device_arena = plib::mempool_arena<plib::aligned_arena<>, 16>; pstring = pstring_t<putf_traits<1, char> >]'
  148 |                         return make_device(pool, anetlist, name, args,
      |                                ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  149 |                                                            std::index_sequence_for<Args...>{});
      |                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Dev/MAME/git_mame/src/lib/netlist/nl_factory.h:155:22:   required from 'netlist::factory::element_t::dev_uptr netlist::factory::device_element_t<C, Args>::make_device(netlist::device_arena&, netlist::netlist_state_t&, const pstring&) [with C = netlist::devices::nld_sys_noise<plib::mersenne_twister_t<long long unsigned int, 64, 312, 156, 31, 13043109905998158313, 29, 6148914691236517205, 17, 8202884508482404352, 37, 18444473444759240704, 43, 6364136223846793005>, plib::normal_distribution_t>; Args = {}; netlist::factory::element_t::dev_uptr = std::unique_ptr<netlist::core_device_t, plib::arena_deleter<plib::mempool_arena<plib::aligned_arena<>, 16>, netlist::core_device_t, 16> >; netlist::device_arena = plib::mempool_arena<plib::aligned_arena<>, 16>; pstring = pstring_t<putf_traits<1, char> >]'
  155 |                         return make_device(pool, anetlist, name, m_args);
      |                                ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Dev/MAME/git_mame/src/lib/netlist/nl_factory.h:152:12:   required from here
  152 |                 dev_uptr make_device(device_arena &pool, netlist_state_t &anetlist,
      |                          ^~~~~~~~~~~
../../../../../src/lib/netlist/plib/prandom.h:162:23: warning: member 'plib::normal_distribution_t<double>::m_buf' is used uninitialized [-Wuninitialized]
  162 |                 : m_p(m_buf.size()), m_stddev(dev) { }
      |                       ^~~~~
In file included from C:/Dev/MAME/buildtools/mingw64/include/c++/15.2.0/bits/new_allocator.h:36,
                 from C:/Dev/MAME/buildtools/mingw64/include/c++/15.2.0/x86_64-w64-mingw32/bits/c++allocator.h:33,
                 from C:/Dev/MAME/buildtools/mingw64/include/c++/15.2.0/bits/allocator.h:46,
                 from C:/Dev/MAME/buildtools/mingw64/include/c++/15.2.0/string:45,
                 from ../../../../../src/lib/netlist/plib/ptypes.h:15,
                 from ../../../../../src/lib/netlist/plib/pstring.h:11,
                 from ../../../../../src/lib/netlist/plib/pexception.h:11,
                 from ../../../../../src/lib/netlist/nl_errstr.h:11,
                 from ../../../../../src/lib/netlist/solver/nld_matrix_solver.h:14,
                 from ../../../../../src/lib/netlist/solver/nld_solver.h:11,
                 from ../../../../../src/lib/netlist/solver/nld_solver.cpp:7:
In function 'std::_Require<std::__not_<std::__is_tuple_like<_Tp> >, std::is_move_constructible<_Tp>, std::is_move_assignable<_Tp> > std::swap(_Tp&, _Tp&) [with _Tp = double]',
    inlined from 'void std::iter_swap(_ForwardIterator1, _ForwardIterator2) [with _ForwardIterator1 = double*; _ForwardIterator2 = double*]' at C:/Dev/MAME/buildtools/mingw64/include/c++/15.2.0/bits/stl_algobase.h:186:11,
    inlined from '_ForwardIterator2 std::swap_ranges(_ForwardIterator1, _ForwardIterator1, _ForwardIterator2) [with _ForwardIterator1 = double*; _ForwardIterator2 = double*]' at C:/Dev/MAME/buildtools/mingw64/include/c++/15.2.0/bits/stl_algobase.h:216:16,
    inlined from 'void std::array<_Tp, _Nm>::swap(std::array<_Tp, _Nm>&) [with _Tp = double; long long unsigned int _Nm = 32]' at C:/Dev/MAME/buildtools/mingw64/include/c++/15.2.0/array:129:25,
    inlined from 'std::__enable_if_t<((bool)typename std::__array_traits<_Tp, _Nm>::_Is_swappable::value)> std::swap(array<_Tp, _Nm>&, array<_Tp, _Nm>&) [with _Tp = double; long long unsigned int _Nm = 32]' at C:/Dev/MAME/buildtools/mingw64/include/c++/15.2.0/array:381:17,
    inlined from 'plib::parray<FT, SIZE, ARENA>& plib::parray<FT, SIZE, ARENA>::operator=(plib::parray<FT, SIZE, ARENA>&&) [with FT = double; int SIZE = -32; ARENA = plib::aligned_arena<>]' at ../../../../../src/lib/netlist/plib/parray.h:122:55,
    inlined from 'plib::parray2D<FT, SIZE1, SIZE2>::parray2D(size_type, size_type) [with FT = double; int SIZE1 = 17; int SIZE2 = -32]' at ../../../../../src/lib/netlist/plib/parray.h:166:17,
    inlined from 'plib::gmres_t<FT, SIZE, RESTARTMAX>::gmres_t(std::size_t) [with FT = double; int SIZE = -32; int RESTARTMAX = 16]' at ../../../../../src/lib/netlist/plib/gmres.h:228:6,
    inlined from 'netlist::solver::matrix_solver_GMRES_t<FT, SIZE>::matrix_solver_GMRES_t(netlist::devices::nld_solver&, const pstring&, netlist::solver::matrix_solver_t::net_list_t&, const netlist::solver::solver_parameters_t*, std::size_t) [with FT = double; int SIZE = -32]' at ../../../../../src/lib/netlist/solver/nld_ms_gmres.h:41:6:
C:/Dev/MAME/buildtools/mingw64/include/c++/15.2.0/bits/move.h:236:11: warning: '*(__vector(2) double*)((char*)&<unnamed> + offsetof(plib::parray<double, -32, plib::aligned_arena<0> >,plib::parray<double, -32, plib::aligned_arena<0> >::m_a.std::array<double, 32>::_M_elems[0]))' may be used uninitialized [-Wmaybe-uninitialized]
  236 |       __a = _GLIBCXX_MOVE(__b);
      |           ^
In file included from ../../../../../src/lib/netlist/plib/pmatrix_cr.h:14,
                 from ../../../../../src/lib/netlist/solver/nld_matrix_solver.h:25:
../../../../../src/lib/netlist/plib/parray.h: In constructor 'netlist::solver::matrix_solver_GMRES_t<FT, SIZE>::matrix_solver_GMRES_t(netlist::devices::nld_solver&, const pstring&, netlist::solver::matrix_solver_t::net_list_t&, const netlist::solver::solver_parameters_t*, std::size_t) [with FT = double; int SIZE = -32]':
../../../../../src/lib/netlist/plib/parray.h:166:54: note: '<anonymous>' declared here
  166 |                                         (*this)[i] = parray<FT, SIZE2>(size2);
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~
In function 'std::_Require<std::__not_<std::__is_tuple_like<_Tp> >, std::is_move_constructible<_Tp>, std::is_move_assignable<_Tp> > std::swap(_Tp&, _Tp&) [with _Tp = double]',
    inlined from 'void std::iter_swap(_ForwardIterator1, _ForwardIterator2) [with _ForwardIterator1 = double*; _ForwardIterator2 = double*]' at C:/Dev/MAME/buildtools/mingw64/include/c++/15.2.0/bits/stl_algobase.h:186:11,
    inlined from '_ForwardIterator2 std::swap_ranges(_ForwardIterator1, _ForwardIterator1, _ForwardIterator2) [with _ForwardIterator1 = double*; _ForwardIterator2 = double*]' at C:/Dev/MAME/buildtools/mingw64/include/c++/15.2.0/bits/stl_algobase.h:216:16,
    inlined from 'void std::array<_Tp, _Nm>::swap(std::array<_Tp, _Nm>&) [with _Tp = double; long long unsigned int _Nm = 32]' at C:/Dev/MAME/buildtools/mingw64/include/c++/15.2.0/array:129:25,
    inlined from 'std::__enable_if_t<((bool)typename std::__array_traits<_Tp, _Nm>::_Is_swappable::value)> std::swap(array<_Tp, _Nm>&, array<_Tp, _Nm>&) [with _Tp = double; long long unsigned int _Nm = 32]' at C:/Dev/MAME/buildtools/mingw64/include/c++/15.2.0/array:381:17,
    inlined from 'plib::parray<FT, SIZE, ARENA>& plib::parray<FT, SIZE, ARENA>::operator=(plib::parray<FT, SIZE, ARENA>&&) [with FT = double; int SIZE = -32; ARENA = plib::aligned_arena<>]' at ../../../../../src/lib/netlist/plib/parray.h:122:55,
    inlined from 'plib::parray2D<FT, SIZE1, SIZE2>::parray2D(size_type, size_type) [with FT = double; int SIZE1 = 17; int SIZE2 = -32]' at ../../../../../src/lib/netlist/plib/parray.h:166:17,
    inlined from 'plib::gmres_t<FT, SIZE, RESTARTMAX>::gmres_t(std::size_t) [with FT = double; int SIZE = -32; int RESTARTMAX = 16]' at ../../../../../src/lib/netlist/plib/gmres.h:228:6,
    inlined from 'netlist::solver::matrix_solver_GMRES_t<FT, SIZE>::matrix_solver_GMRES_t(netlist::devices::nld_solver&, const pstring&, netlist::solver::matrix_solver_t::net_list_t&, const netlist::solver::solver_parameters_t*, std::size_t) [with FT = double; int SIZE = -32]' at ../../../../../src/lib/netlist/solver/nld_ms_gmres.h:41:6:
C:/Dev/MAME/buildtools/mingw64/include/c++/15.2.0/bits/move.h:236:11: warning: '*(__vector(2) double*)((char*)&<unnamed> + offsetof(plib::parray<double, -32, plib::aligned_arena<0> >,plib::parray<double, -32, plib::aligned_arena<0> >::m_a.std::array<double, 32>::_M_elems[2]))' may be used uninitialized [-Wmaybe-uninitialized]
  236 |       __a = _GLIBCXX_MOVE(__b);
      |           ^
../../../../../src/lib/netlist/plib/parray.h: In constructor 'netlist::solver::matrix_solver_GMRES_t<FT, SIZE>::matrix_solver_GMRES_t(netlist::devices::nld_solver&, const pstring&, netlist::solver::matrix_solver_t::net_list_t&, const netlist::solver::solver_parameters_t*, std::size_t) [with FT = double; int SIZE = -32]':
../../../../../src/lib/netlist/plib/parray.h:166:54: note: '<anonymous>' declared here
  166 |                                         (*this)[i] = parray<FT, SIZE2>(size2);
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~
(...)
Archiving libnetlist.a...
Compiling generated/version.cpp...
Emitting mame_mame_vers.rc...
Compiling resources generated/resource/mame_mame_vers.rc...
Linking mame.exe...
```

**Comment by joshuashaffer** [comment]
@happppp @rb6502 

```
Compiling src/emu/http.cpp...
In file included from ../../../../../src/emu/http.cpp:18:
../../../../../src/lib/util/server_http_impl.hpp: In instantiation of ‘webpp::ServerBase<socket_type>::Request::Request(const socket_type&) [with socket_type = asio::basic_stream_socket<asio::ip::tcp>]’:
../../../../../src/lib/util/server_http_impl.hpp:472:59:   required from here
../../../../../src/lib/util/server_http_impl.hpp:104:69: error: member ‘webpp::ServerBase<asio::basic_stream_socket<asio::ip::tcp> >::Request::streambuf’ is used uninitialized [-Werror=uninitialize]
  104 |                         Request(const socket_type &socket): content(streambuf) {
      |                                                                     ^~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [emu.make:1360: ../../../../linux_gcc/obj/x64/Release/src/emu/http.o] Error 1
make[1]: *** [Makefile:97: emu] Error 2
make: *** [makefile:1240: linux_x64] Error 2
```

```
Compiling src/lib/netlist/devices/nld_74123.cpp...
Compiling src/lib/netlist/devices/nld_system.cpp...
In file included from ../../../../../src/lib/netlist/devices/nlid_system.h:13,
                 from ../../../../../src/lib/netlist/devices/nld_system.cpp:9:
../../../../../src/lib/netlist/plib/prandom.h: In instantiation of ‘plib::normal_distribution_t<FT>::normal_distribution_t(FT) [with FT = double]’:
../../../../../src/lib/netlist/devices/nlid_system.h:562:5:   required from ‘netlist::devices::nld_sys_noise<E, D>::nld_sys_noise(netlist::device_t::constructor_param_t) [with E = plib::mersenne_twister_t<long unsigned int, 64, 312, 156, 31, 13043109905998158313, 29, 6148914691236517205, 17, 8202884508482404352, 37, 18444473444759240704, 43, 6364136223846793005>; D = plib::normal_distribution_t; netlist::device_t::constructor_param_t = const netlist::core_device_data_t&]’
../../../../../src/lib/netlist/solver/../core/../plib/palloc.h:569:12:   required from ‘T* plib::detail::alloc(ARENA&, Args&& ...) [with T = netlist::devices::nld_sys_noise<plib::mersenne_twister_t<long unsigned int, 64, 312, 156, 31, 13043109905998158313, 29, 6148914691236517205, 17, 8202884508482404352, 37, 18444473444759240704, 43, 6364136223846793005>, plib::normal_distribution_t>; long unsigned int ALIGN = 0; ARENA = plib::mempool_arena<plib::aligned_arena<>, 16>; Args = {netlist::core_device_data_t}]’
../../../../../src/lib/netlist/solver/../core/../plib/palloc.h:641:38:   required from ‘typename ARENA::unique_ptr<T, ALIGN> plib::make_unique(ARENA&, Args&& ...) [with T = netlist::devices::nld_sys_noise<mersenne_twister_t<long unsigned int, 64, 312, 156, 31, 13043109905998158313, 29, 6148914691236517205, 17, 8202884508482404352, 37, 18444473444759240704, 43, 6364136223846793005>, normal_distribution_t>; ARENA = mempool_arena<aligned_arena<>, 16>; long unsigned int ALIGN = 0; Args = {netlist::core_device_data_t}; typename ARENA::unique_ptr<T, ALIGN> = std::unique_ptr<netlist::devices::nld_sys_noise<mersenne_twister_t<long unsigned int, 64, 312, 156, 31, 13043109905998158313, 29, 6148914691236517205, 17, 8202884508482404352, 37, 18444473444759240704, 43, 6364136223846793005>, normal_distribution_t>, arena_deleter<mempool_arena<aligned_arena<>, 16>, netlist::devices::nld_sys_noise<mersenne_twister_t<long unsigned int, 64, 312, 156, 31, 13043109905998158313, 29, 6148914691236517205, 17, 8202884508482404352, 37, 18444473444759240704, 43, 6364136223846793005>, normal_distribution_t>, 16> >]’
../../../../../src/lib/netlist/solver/../core/../nl_factory.h:140:31:   required from ‘netlist::factory::element_t::dev_uptr netlist::factory::device_element_t<C, Args>::make_device(netlist::device_arena&, netlist::netlist_state_t&, const pstring&, std::tuple<_UTypes ...>&, std::index_sequence<Is ...>) [with long unsigned int ...Is = {}; C = netlist::devices::nld_sys_noise<plib::mersenne_twister_t<long unsigned int, 64, 312, 156, 31, 13043109905998158313, 29, 6148914691236517205, 17, 8202884508482404352, 37, 18444473444759240704, 43, 6364136223846793005>, plib::normal_distribution_t>; Args = {}; netlist::factory::element_t::dev_uptr = std::unique_ptr<netlist::core_device_t, plib::arena_deleter<plib::mempool_arena<plib::aligned_arena<>, 16>, netlist::core_device_t, 16> >; netlist::device_arena = plib::mempool_arena<plib::aligned_arena<>, 16>; pstring = pstring_t<putf_traits<1, char> >; std::index_sequence<Is ...> = std::integer_sequence<long unsigned int>]’
../../../../../src/lib/netlist/solver/../core/../nl_factory.h:148:22:   required from ‘netlist::factory::element_t::dev_uptr netlist::factory::device_element_t<C, Args>::make_device(netlist::device_arena&, netlist::netlist_state_t&, const pstring&, std::tuple<_UTypes ...>&) [with C = netlist::devices::nld_sys_noise<plib::mersenne_twister_t<long unsigned int, 64, 312, 156, 31, 13043109905998158313, 29, 6148914691236517205, 17, 8202884508482404352, 37, 18444473444759240704, 43, 6364136223846793005>, plib::normal_distribution_t>; Args = {}; netlist::factory::element_t::dev_uptr = std::unique_ptr<netlist::core_device_t, plib::arena_deleter<plib::mempool_arena<plib::aligned_arena<>, 16>, netlist::core_device_t, 16> >; netlist::device_arena = plib::mempool_arena<plib::aligned_arena<>, 16>; pstring = pstring_t<putf_traits<1, char> >]’
../../../../../src/lib/netlist/solver/../core/../nl_factory.h:155:22:   required from ‘netlist::factory::element_t::dev_uptr netlist::factory::device_element_t<C, Args>::make_device(netlist::device_arena&, netlist::netlist_state_t&, const pstring&) [with C = netlist::devices::nld_sys_noise<plib::mersenne_twister_t<long unsigned int, 64, 312, 156, 31, 13043109905998158313, 29, 6148914691236517205, 17, 8202884508482404352, 37, 18444473444759240704, 43, 6364136223846793005>, plib::normal_distribution_t>; Args = {}; netlist::factory::element_t::dev_uptr = std::unique_ptr<netlist::core_device_t, plib::arena_deleter<plib::mempool_arena<plib::aligned_arena<>, 16>, netlist::core_device_t, 16> >; netlist::device_arena = plib::mempool_arena<plib::aligned_arena<>, 16>; pstring = pstring_t<putf_traits<1, char> >]’
../../../../../src/lib/netlist/solver/../core/../nl_factory.h:152:12:   required from here
../../../../../src/lib/netlist/plib/prandom.h:162:23: error: member ‘plib::normal_distribution_t<double>::m_buf’ is used uninitialized [-Werror=uninitialized]
  162 |                 : m_p(m_buf.size()), m_stddev(dev) { }
      |                       ^~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [netlist.make:1167: ../../../../linux_gcc/obj/x64/Release/src/lib/netlist/devices/nld_system.o] Error 1
make[1]: *** [Makefile:28: netlist] Error 2
make: *** [makefile:1240: linux_x64] Error 2
```

Not "churn." Member order and initialization order absolutely matter in C++.
