### ISSUE TITLE
bgfx: metal renderer: pixel-format build errors for macOS 10.14 and 10.15

### ISSUE THREAD

**Issue by mascguy** [mamedev/mame#11245]
### MAME version

0.254

### System information

MacPorts port of Mame

macOS 10.14, Xcode 10.3
macOS 10.15, Xcode 12.0

### Incorrect behaviour

Starting with version 0.252, compilation errors occur for BGFX's Metal renderer: `3rdparty/bgfx/src/renderer_mtl.mm`. They appear related to Metal pixel formats used, some of which apparently (?) aren't available for macOS releases prior to Big Sur.

While it's been awhile since we discussed the topic, the last I understood - and per the current build instructions on `mamedev.org` - Mame is supposed to support macOS 10.14 and later. Is that still the case?

In any event, the specific failures are as follows, specifically for 0.254. (Note: I eliminated line numbers, and collapsed these down to the unique set of identifiers.)

For 10.14:

```
renderer_mtl.mm:: error: unknown type name 'MTLTextureSwizzleChannels'
renderer_mtl.mm:: error: use of undeclared identifier 'MTLTextureSwizzleAlpha'
renderer_mtl.mm:: error: use of undeclared identifier 'MTLTextureSwizzleBlue'
renderer_mtl.mm:: error: use of undeclared identifier 'MTLTextureSwizzleGreen'
renderer_mtl.mm:: error: use of undeclared identifier 'MTLTextureSwizzleRed'
```

For 10.15:

```
renderer_mtl.mm: error: 'MTLPixelFormatABGR4Unorm' is unavailable: not available on macOS
renderer_mtl.mm: error: 'MTLPixelFormatB5G6R5Unorm' is unavailable: not available on macOS
renderer_mtl.mm: error: 'MTLPixelFormatBGR5A1Unorm' is unavailable: not available on macOS
```

### Expected behaviour

Per the official build instructions on `mamedev.org`, macOS 10.14 and later should still be supported. As such, it would be great if some `#ifdef`'s could be added, to do the right thing for 10.14 and 10.15. But can you folks confirm that you still support 10.14 and up?

### Steps to reproduce

Build Mame on either 10.14 or 10.15. It's that simple.

**Comment by MooglyGuy** [comment]
The compile errors you're citing are in a 3rd-party library that is unmodified by MAME, please verify against upstream BGFX before reporting issues like these.

**Comment by mascguy** [comment]
> The compile errors you're citing are in a 3rd-party library that is unmodified by MAME, please verify against upstream BGFX before reporting issues like these.

While I'm fine with that, are you folks still officially supporting 10.14 and later? If so, I would think you folks would want to track this as well.

CC: @cuavas

**Comment by mascguy** [comment]
> > The compile errors you're citing are in a 3rd-party library that is unmodified by MAME, please verify against upstream BGFX before reporting issues like these.
> 
> While I'm fine with that, are you folks still officially supporting 10.14 and later? If so, I would think you folks would want to track this as well.
> 
> CC: @cuavas

One question: While it would be easy enough to patch the issue, will that cause downstream failures (compilation or runtime) within Mame? It would help to understand what the implications are, if certain pixel formats are unavailable.

**Comment by MooglyGuy** [comment]
> > The compile errors you're citing are in a 3rd-party library that is unmodified by MAME, please verify against upstream BGFX before reporting issues like these.
> 
> While I'm fine with that, are you folks still officially supporting 10.14 and later? If so, I would think you folks would want to track this as well.

There's no need to tag in a team member who doesn't run macOS.

The MAME team unfortunately doesn't have the sort of money to have a fleet of macOS machines to test each macOS version and deprecate them in turn, there's a reliance on the small handful of people who run macOS to report when something has broken.

Since you seem to be on an affected system, would it be possible for you to try grabbing the latest upstream BGFX code, copy it into place, and try building MAME to see if this resolves the issue?

**Comment by mascguy** [comment]
> > While I'm fine with that, are you folks still officially supporting 10.14 and later? If so, I would think you folks would want to track this as well.
> 
> There's no need to tag in a team member who doesn't run macOS.

I specifically CCed Vas, as we've corresponded in the past. And he knows what my role is: I'm the official maintainer of Mame, for MacPorts:

https://ports.macports.org/port/mame/details

> The MAME team unfortunately doesn't have the sort of money to have a fleet of macOS machines to test each macOS version and deprecate them in turn, there's a reliance on the small handful of people who run macOS to report when something has broken.
> 
> Since you seem to be on an affected system, would it be possible for you to try grabbing the latest upstream BGFX code, copy it into place, and try building MAME to see if this resolves the issue?

Bear in mind that I am not reporting this issue on behalf of myself personally. Rather, I'm reporting it on behalf of **all** of our users. There's a big difference! (That's not meant to be taken in a defensive tone, but rather, simply informing you of who I am... and what my role is.)

I'm certainly happy to test with the latest upstream code, but let's assume that the issue still exists. If we (MacPorts) patch the code to drop the affected pixel formats for 10.14 and 10.15, will that cause runtime issues within Mame?

**Comment by MooglyGuy** [comment]
Unsubscribing

**Comment by mascguy** [comment]
@cuavas/Anyone, as a heads-up, it appears that BGFX now targets Big Sur and later exclusively. Which is at odds with the goal of supporting 10.14 and 10.15.

While I'm happy to work with them as well, just a heads-up relative to platform support.

**Comment by rb6502** [comment]
Hi!  Please try this patch: https://gist.github.com/rb6502/8a1736ee3775f998e8e71faa47ae4b59

I can't apply it to mainline so you'll need to re-patch MAME with it for each new release.  It seems to not affect anything we currently do with BGFX, but I can't guarantee it will remain that way in the future.

**Comment by mietek** [comment]
FWIW, as I’m still stuck on macOS 10.14 for development, I’ve been working around this problem for myself by building MAME with `make ARCHOPTS='-DBGFX_CONFIG_RENDERER_METAL=0'`.

**Comment by mascguy** [comment]
> Hi! Please try this patch: [gist.github.com/rb6502/8a1736ee3775f998e8e71faa47ae4b59](https://gist.github.com/rb6502/8a1736ee3775f998e8e71faa47ae4b59)
> 
> I can't apply it to mainline without making myself puke, let alone @cuavas, so you'll need to re-patch MAME with it for each new release. It seems to not affect anything we currently do with BGFX, but I can't guarantee it will remain that way in the future. On the plus side, builds for Big Sur and later are unchanged relative to MAME mainline.

Hey Rob, sorry for the delayed response on this, juggling a bit too much these days.

For your patch, it works on either 10.14 or 10.15 (can't remember which), but not the other. So it looks like we might need further conditional checks, applying slightly different changes between those two macOS releases...? (Haven't dug into this too much though, so can't provide any better suggestions at this point.)

So for now, we went with the suggestion from @mietek, and simply disabled the Metal renderer for 10.14/10.15.

But if it would be possible to tweak the patch to support both macOS releases, we'd gladly take advantage of it. Assuming it's not going to be problematic for future Mame/BGFX releases, per your point.

Your thoughts...?

**Comment by mietek** [comment]
Using the most recent `master`, compiling on macOS 10.14 fails with multiple errors such as these:
```
In file included from ../../../../../3rdparty/bx/include/bx/allocator.h:9:
../../../../../3rdparty/bx/include/bx/bx.h:75:30: error: use of undeclared identifier '__builtin_FILE'
                          const char* _filePath = __builtin_FILE()
                                                  ^
../../../../../3rdparty/bx/include/bx/bx.h:76:23: error: use of undeclared identifier '__builtin_LINE'
                        , uint32_t _line = __builtin_LINE()
                                           ^
../../../../../3rdparty/bx/include/bx/bx.h:103:30: error: use of undeclared identifier '__builtin_FUNCTION'
                          const char* _function = __builtin_FUNCTION()
                                                  ^
../../../../../3rdparty/bx/include/bx/bx.h:104:30: error: use of undeclared identifier '__builtin_FILE'
                        , const char* _filePath = __builtin_FILE()
                                                  ^
../../../../../3rdparty/bx/include/bx/bx.h:105:23: error: use of undeclared identifier '__builtin_LINE'
                        , uint32_t _line = __builtin_LINE()
                                           ^
```

**Comment by belegdol** [comment]
> Using the most recent `master`, compiling on macOS 10.14 fails with multiple errors such as these:
> 
> ```
> In file included from ../../../../../3rdparty/bx/include/bx/allocator.h:9:
> ../../../../../3rdparty/bx/include/bx/bx.h:75:30: error: use of undeclared identifier '__builtin_FILE'
>                           const char* _filePath = __builtin_FILE()
>                                                   ^
> ../../../../../3rdparty/bx/include/bx/bx.h:76:23: error: use of undeclared identifier '__builtin_LINE'
>                         , uint32_t _line = __builtin_LINE()
>                                            ^
> ../../../../../3rdparty/bx/include/bx/bx.h:103:30: error: use of undeclared identifier '__builtin_FUNCTION'
>                           const char* _function = __builtin_FUNCTION()
>                                                   ^
> ../../../../../3rdparty/bx/include/bx/bx.h:104:30: error: use of undeclared identifier '__builtin_FILE'
>                         , const char* _filePath = __builtin_FILE()
>                                                   ^
> ../../../../../3rdparty/bx/include/bx/bx.h:105:23: error: use of undeclared identifier '__builtin_LINE'
>                         , uint32_t _line = __builtin_LINE()
>                                            ^
> ```

This would be my fault. Does @rb6502 unofficial patch still apply?

**Comment by belegdol** [comment]
`__builtin_FILE()` seems to be something provided by GCC according to Google. Which versions does the affected macOS come with?

**Comment by cuavas** [comment]
macOS hasn’t used GCC for years, and never used GNU libc (it always used libsystem like NeXT).

**Comment by belegdol** [comment]
Well in any case it is something compiler is supposed to provide.
Could you try applying https://github.com/bkaradzic/bx/commit/a00ecbc9d58833d4ae4e28b34644b93cde81ebb7 in reverse to see if it helps?

**Comment by cuavas** [comment]
> Well in any case it is something compiler is supposed to provide.

No, it’s a non-standard extension that GCC happens to provide.  But seriously, if the amount of upstream stuff that needs reverting increases, I’m just going to back this out.  The bgfx update seems to be more problems than anything else.

**Comment by belegdol** [comment]
I slowly tend to agree. Upstream bgfx and friends does not seem to care too much about being backwards compatible on mac too whatsoever which appears to be at odds with mame goals. I could ship the bgfx update and Wayland support in Fedora RPM as a downstream patch. This way we could get some exposure and will know how good or bad it works next time we are ready to lift mac requirements.

**Comment by cuavas** [comment]
> I could ship the bgfx update and Wayland support in Fedora RPM as a downstream patch. This way we could get some exposure and will know how good or bad it works next time we are ready to lift mac requirements.

If you do this, please ensure your users are aware that it’s diverged from mainline, and don’t send issues with bgfx shaders our way.

**Comment by rb6502** [comment]
Clang usually supports all of the GCC extensions so I'm a little surprised about this.  Then again 10.14 is Clang 8 if you're using the official packages and the current Xcode bleeding edge is Clang 16.

**Comment by belegdol** [comment]
The bgfx update has been rolled back now.

**Comment by wyatt-wong** [comment]
> https://gist.github.com/rb6502/8a1736ee3775f998e8e71faa47ae4b59

I encountered the SAME issue which you mentioned as I am using macOS 10.15.7, so how to resolve it ?

```
...
...
Compiling src/mame/capcom/1942.cpp...
../../../../../3rdparty/bgfx/src/renderer_mtl.mm:323:5: error: 
      'MTLPixelFormatB5G6R5Unorm' is unavailable: not available on macOS
                { MTLPixelFormatB5G6R5Unorm,                    MTLPixel...
                  ^
In file included from ../../../../../3rdparty/bgfx/src/renderer_mtl.mm:10:
In file included from ../../../../../3rdparty/bgfx/src/renderer_mtl.h:13:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLPixelFormat.h:43:5: note: 
      'MTLPixelFormatB5G6R5Unorm' has been explicitly marked unavailable here
    MTLPixelFormatB5G6R5Unorm API_AVAILABLE(ios(8.0)) API_UNAVAILABLE(ma...
    ^
../../../../../3rdparty/bgfx/src/renderer_mtl.mm:324:5: error: 
      'MTLPixelFormatB5G6R5Unorm' is unavailable: not available on macOS
                { MTLPixelFormatB5G6R5Unorm,                    MTLPixel...
                  ^
In file included from ../../../../../3rdparty/bgfx/src/renderer_mtl.mm:10:
In file included from ../../../../../3rdparty/bgfx/src/renderer_mtl.h:13:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLPixelFormat.h:43:5: note: 
      'MTLPixelFormatB5G6R5Unorm' has been explicitly marked unavailable here
    MTLPixelFormatB5G6R5Unorm API_AVAILABLE(ios(8.0)) API_UNAVAILABLE(ma...
    ^
../../../../../3rdparty/bgfx/src/renderer_mtl.mm:325:5: error: 
      'MTLPixelFormatABGR4Unorm' is unavailable: not available on macOS
                { MTLPixelFormatABGR4Unorm,                     MTLPixel...
                  ^
In file included from ../../../../../3rdparty/bgfx/src/renderer_mtl.mm:10:
In file included from ../../../../../3rdparty/bgfx/src/renderer_mtl.h:13:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLPixelFormat.h:45:5: note: 
      'MTLPixelFormatABGR4Unorm' has been explicitly marked unavailable here
    MTLPixelFormatABGR4Unorm  API_AVAILABLE(ios(8.0)) API_UNAVAILABLE(ma...
    ^
../../../../../3rdparty/bgfx/src/renderer_mtl.mm:326:5: error: 
      'MTLPixelFormatABGR4Unorm' is unavailable: not available on macOS
                { MTLPixelFormatABGR4Unorm,                     MTLPixel...
                  ^
In file included from ../../../../../3rdparty/bgfx/src/renderer_mtl.mm:10:
In file included from ../../../../../3rdparty/bgfx/src/renderer_mtl.h:13:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLPixelFormat.h:45:5: note: 
      'MTLPixelFormatABGR4Unorm' has been explicitly marked unavailable here
    MTLPixelFormatABGR4Unorm  API_AVAILABLE(ios(8.0)) API_UNAVAILABLE(ma...
    ^
../../../../../3rdparty/bgfx/src/renderer_mtl.mm:327:5: error: 
      'MTLPixelFormatBGR5A1Unorm' is unavailable: not available on macOS
                { MTLPixelFormatBGR5A1Unorm,                    MTLPixel...
                  ^
In file included from ../../../../../3rdparty/bgfx/src/renderer_mtl.mm:10:
In file included from ../../../../../3rdparty/bgfx/src/renderer_mtl.h:13:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLPixelFormat.h:46:5: note: 
      'MTLPixelFormatBGR5A1Unorm' has been explicitly marked unavailable here
    MTLPixelFormatBGR5A1Unorm API_AVAILABLE(ios(8.0)) API_UNAVAILABLE(ma...
    ^
../../../../../3rdparty/bgfx/src/renderer_mtl.mm:328:5: error: 
      'MTLPixelFormatBGR5A1Unorm' is unavailable: not available on macOS
                { MTLPixelFormatBGR5A1Unorm,                    MTLPixel...
                  ^
In file included from ../../../../../3rdparty/bgfx/src/renderer_mtl.mm:10:
In file included from ../../../../../3rdparty/bgfx/src/renderer_mtl.h:13:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAMetalLayer.h:8:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLPixelFormat.h:46:5: note: 
      'MTLPixelFormatBGR5A1Unorm' has been explicitly marked unavailable here
    MTLPixelFormatBGR5A1Unorm API_AVAILABLE(ios(8.0)) API_UNAVAILABLE(ma...
    ^
6 errors generated.
make[2]: *** [bgfx.make:591: ../../../../osx_clang/obj/x64/Release/3rdparty/bgfx/src/renderer_mtl.o] Error 1
make[1]: *** [Makefile:76: bgfx] Error 2
```

**Comment by cuavas** [comment]
We no longer officially support versions of macOS older than 11.0 “Big Sur”.  People can discuss unofficial workarounds for building on older operating systems on discussion forums.
