### ISSUE TITLE
Compile error on macOS 26.4 with Xcode 26.4 (Cland 21.0.0) for mame0287

### ISSUE THREAD

**Issue by neoswallow** [mamedev/mame#15174]
### MAME version

0.287

### System information

macOS 26.4
MacStudio M4 Max 128GB RAM

### INI configuration details

```INI

```

### Incorrect behaviour

[log entries near the error]
Clang 21.0.0 detected
…
Compiling src/devices/machine/ie15.cpp...
Archiving liboptional.a...
make: *** [macosx_arm64_clang] Error 2

### Expected behaviour

[log entries of the same location on the previous version, 0.286 or older]
Clang 17.0.0 detected
…
Compiling src/devices/machine/ie15.cpp...
Archiving liboptional.a...
Compiling src/mame/mame.cpp...
…

### Steps to reproduce

git checkout tags/mame0287
make REGENIE=1 TOOLS=1 -j17

### Additional details

When I compared logs on 0.287 failure vs successful ones from the last a couple versions, I see that previous couple versions were built using clang 17.0.0 and now it's clang 21.0.0.
Since clang is from Xcode developer tools, I presume Apple updated clang to 21 from 17 with Xcode 26.4.

**Comment by rb6502** [comment]
That's odd.  I'm running Tahoe 26.4 and Xcode 26.4 is installed, but Clang is still 17.

**Comment by neoswallow** [comment]
> That's odd. I'm running Tahoe 26.4 and Xcode 26.4 is installed, but Clang is still 17.

Hmm.
```shell
which -a clang
/usr/bin/clang

clang --version
Apple clang version 21.0.0 (clang-2100.0.123.102)
Target: arm64-apple-darwin25.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by rb6502** [comment]
Ok.  What's `xcode-select -p` print on your system?

**Comment by rb6502** [comment]
Never mind, I ran the Xcode GUI and found that Settings -> Locations had the Command Line Tools set to something unknown.  Selecting "Xcode 26.4" there got me Clang 21 on the command line.  Let me see what's wrong.

**Comment by rb6502** [comment]
Ok.  Github top of tree seems to build OK with Clang 21, likely due to @cuavas ' just-landed C++20 compliance updates.  Can you give that a try?

**Comment by neoswallow** [comment]
Just tried current head 747a9a but I still got the same error. 😞

**Comment by rb6502** [comment]
Hmm.  Can you find the actual error, or rebuild without any -j options so it goes one file at a time?  Then it will stop at the actual failure.

**Comment by neoswallow** [comment]
Also tried eea4b4 which is the commit for that C++20 support, again with the same error.
I will try the sequential build to see where exactly it stops.

**Comment by rb6502** [comment]
Oh, do you have SDL3 installed?  That would be important.

**Comment by neoswallow** [comment]
```
Compiling src/osd/sdl3/sdlmain.cpp...
../../../../../src/osd/sdl3/sdlmain.cpp:89:14: error: use of undeclared identifier 'SDL_HINT_MAC_PRESS_AND_HOLD'
   89 |         SDL_SetHint(SDL_HINT_MAC_PRESS_AND_HOLD, 0);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [../../../../osx_clang/obj/x64/Release/osd_sdl3/src/osd/sdl3/sdlmain.o] Error 1
make[1]: *** [osd_sdl3] Error 2
make: *** [macosx_arm64_clang] Error 2
```
Yes, I do have both SDL2.32.10 and SDL3.2.30 installed.

**Comment by rb6502** [comment]
I added support for telling SDL3 not to pop up the accents thing when you hold keys down on macOS, but that feature requires SDL 3.4.0.  3.4.2 seems like it's generally a good idea on macOS anyway because it fixes several gamepad support problems, but I've also checked in a fix that should allow it to build with 3.2.x again as well.

**Comment by neoswallow** [comment]
So, should I test with both 3.2.x and 3.4.2 and see if it compiles with both versions?

**Comment by neoswallow** [comment]
So I can confirm that it was SDL3 version issue.
With your fix, I can now build with SDL 3.2.x.
I'll test 0.287 tag with SDL 3.4.x to confirm that the build failure indeed was with SDL3.
FYI, I only installed SDL 3.2.x because I thought I read that 3.4.x was going to have breaking changes from 3.2.x in one of the release notes but I don't remember for sure.

**Comment by neoswallow** [comment]
I can now confirm that mame0287 tag does indeed compile without any error if you have SDL 3.4.x installed, with clang 21.0.0.
Thank you.
I'll now close the issue.
