### ISSUE TITLE
Building with system Lua and SQLite3 does not work

### ISSUE THREAD

**Issue by jmallach** [mamedev/mame#711]
I'm trying to get 0.171 to build on Debian unstable, using lua 5.3 and sqlite3 from the system.

Setting USE_SYSTEM_LIB_LUA, USE_SYSTEM_LIB_SQLITE3 and USE_SYSTEM_SQLITE all make the build fail with:

Compiling 3rdparty/lsqlite3/lsqlite3.c...
../../../../../3rdparty/lsqlite3/lsqlite3.c:34:17: fatal error: lua.h: No such file or directory
compilation terminated.
lualibs.make:258: recipe for target '../../../../linux_gcc/obj/x64/Release/3rdparty/lsqlite3/lsqlite3.o' failed

(Note the build system always seems to want to compile this 3rdparty module regardless what genie defined)

Unsetting these variables works, but that means compiling in a lib that many distributions would reject.

**Comment by belegdol** [comment]
You can't build using system lua-sqlite yet, only system lua and system sqlite. Can you try defining USE_SYSTEM_LIB_LUA and USE_SYSTEM_LIB_SQLITE3 only?
Are you deleting anything from the 3rdparty folder?

**Comment by jmallach** [comment]
I've tried using only USE_SYSTEM_LIB_LUA and USE_SYSTEM_LIB_SQLITE3, me adding USE_SYSTEM_SQLITE was a bit desperate after reading through the build system. With only the two I'd expect, it errors out as I said above. Why isn't it supported?

**Comment by belegdol** [comment]
Building using system lua-sqlite is not supported yet as noone has sent necessary patches yet. It's on my to-do but as lua-sqlite is not packaged in fedora yet this might take a while.
Anyway, using system sqlite and lua should work, it does in my Fedora packages. The error you posted indicates that lua headers are missing. You still need lua in 3rdparty folder to build lua-sqlite, even if you are building using system lua.

**Comment by jmallach** [comment]
Thanks for your comment Julian. I'm quite sure this is going to be a prerequisite before I can upload a GPL MAME to Debian, so any hint on what needs to be done would be very useful for me in order to try patch this myself. Thanks!

**Comment by jmallach** [comment]
To be clear, I haven't removed any folder from 3rdparty. ie, the build fails even if the lua sources are in 3rd party, when telling the build system to build using system lua. For now, I'll be building with the bundled lua.

This currently fails with lua 5.2 and 5.3 in Debian, for the record.

**Comment by h0tw1r3** [comment]
@jmallach Can you point me to Debian's lsqlite3 package? (http://lua.sqlite.org/index.cgi/index)

**Comment by jmallach** [comment]
@h0tw1r3, see here: https://tracker.debian.org/pkg/lua-sql

**Comment by h0tw1r3** [comment]
@jmallach I think that is where the confusion is. lsqlite3 is completely different than lua-sql (and lua-sql-sqlite).

**Comment by jmallach** [comment]
OK, I guess I'm too Lua illiterate. :D
Can the build system be made to accept Lua from system, sqlite3 from the system and lsqlite3 from 3rdparty?

**Comment by h0tw1r3** [comment]
Yes, it works that way right now.

**Comment by jmallach** [comment]
I get a build failure with that build config, as the initial report states. That is, with Debian packages liblua5.2-dev and libsqlite3-dev and defined USE_SYSTEM_LIB_LUA and USE_SYSTEM_LIB_SQLITE3.

**Comment by h0tw1r3** [comment]
Mame's build system doesn't do much for you when you tell it to use system libraries. It tries to include the standard locations for headers, and that's it. You need to do the rest of the work yourself.

That said, set `OPT_FLAGS = -I/usr/include/lua5.2` in the `makefile`.

After that you'll run into another problem. Looks like mame doesn't support lua 5.2 :8ball: So to compile on Debian Jessie, you'll need to use backports, stick with the 3rdparty supplied library, or create a patch for backwards compatibility (might be as simple as a header with some ifdefs).

**Comment by jmallach** [comment]
dpkg-deb: building package 'mame' in '../mame_0.172-1_amd64.deb'.

 Depends: libc6 (>= 2.14), libexpat1 (>= 2.0.1), libflac8 (>= 1.3.0), libfontconfig1 (>= 2.11), libgcc1 (>= 1:3.0), libgl1-mesa-glx | libgl1, libjpeg62-turbo (>= 1.3.1), liblua5.3-0, libportmidi0, libqt5core5a (>= 5.5.0), libqt5gui5 (>= 5.0.2), libqt5widgets5 (>= 5.0.2), libsdl2-2.0-0 (>= 2.0.4), libsdl2-ttf-2.0-0 (>= 2.0.14), libsqlite3-0 (>= 3.5.9), libstdc++6 (>= 5.2), libx11-6, zlib1g (>= 1:1.2.2), mame-data (= 0.172-1)

Thanks @h0tw1r3 for a last minute fix. This made it easy to build with system lua with no additional hacks!

I'll open a separate issue as I don't seem to be able to get system libuv working like this though.
